import 'package:flutter/material.dart';
import 'package:speedmart_lanka/core/utils/sri_lanka_phone_helper.dart';
import 'package:speedmart_lanka/core/utils/validators.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter/services.dart';
import 'package:go_router/go_router.dart';
import 'package:latlong2/latlong.dart';

import '../core/services/connectivity_service.dart';
import '../features/auth/providers/auth_provider.dart';
import '../features/auth/customer_registration/providers/customer_registration_provider.dart';
import '../features/customer/delivery_address/models/customer_delivery_address.dart';
import '../features/customer/delivery_address/providers/customer_delivery_address_provider.dart';
import '../features/location/data/sri_lanka_data.dart';
import '../features/location/models/sri_lanka_province.dart';
import '../features/location/models/sri_lanka_district.dart';
import '../features/location/services/gps_location_service.dart';
import '../features/location/services/reverse_geocoding_service.dart';
import '../shared/models/user_role.dart';
import '../shared/models/user_model.dart';
import '../core/routes/route_names.dart';
import '../core/storage/storage_service.dart';

import 'sri_lanka_customer_login_figma.dart';
import 'sri_lanka_customer_login_otp_figma.dart';
import 'sri_lanka_customer_register_figma.dart';
import 'sri_lanka_customer_register_otp_figma.dart';

import 'sri_lanka_vendor_login_figma.dart';
import 'sri_lanka_vendor_login_otp_figma.dart';
import 'sri_lanka_vendor_register_figma.dart';
import 'sri_lanka_vendor_register_otp_figma.dart';

import 'sri_lanka_vendor_forget_password_figma.dart';
import 'sri_lanka_vendor_forget_password_otp_figma.dart';
import 'new_password_update_sri_lanka_vendor_figma.dart';
import '../shared/widgets/auth_loading_overlay.dart';


enum FigmaAuthRole { customer, vendor }

enum _FigmaAuthPage {
  customerLogin,
  customerLoginOtp,
  customerRegister,
  customerRegisterOtp,
  vendorLogin,
  vendorLoginOtp,
  vendorRegister,
  vendorRegisterOtp,
  vendorForgotPassword,
  vendorForgotPasswordOtp,
  vendorNewPassword,
}

class FigmaAuthFlow extends ConsumerStatefulWidget {
  const FigmaAuthFlow({super.key, required this.role});
  final FigmaAuthRole role;

  @override
  ConsumerState<FigmaAuthFlow> createState() => _FigmaAuthFlowState();
}

class _FigmaAuthFlowState extends ConsumerState<FigmaAuthFlow>
  with SingleTickerProviderStateMixin, WidgetsBindingObserver {
  _FigmaAuthPage _page = _FigmaAuthPage.customerLogin;
  _FigmaAuthPage? _prevPage;

  late final AnimationController _animCtrl;
  late final Animation<Offset> _inSlide;
  late final Animation<Offset> _outSlide;
  // direction multiplier: +1 = forward, -1 = back
  final _dirNotifier = ValueNotifier<double>(1.0);

  final _customerLoginOtpKey = GlobalKey<SrilankacustomerloginotpWidgetState>();
  final _customerRegisterOtpKey = GlobalKey<SrilankacustomerregistrationotpWidgetState>();
  final _vendorLoginOtpKey = GlobalKey<SrilankavendorloginotpWidgetState>();
  final _vendorRegisterOtpKey = GlobalKey<SrilankavendorregistrationotpWidgetState>();



  // â”€â”€ Registration form state â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  // Login phone
  final _loginPhoneCtrl = TextEditingController();

  // Vendor login controllers â€” passed into figma login widgets
  final _vendorLoginEmailCtrl = TextEditingController();
  final _vendorLoginPasswordCtrl = TextEditingController();

  // Vendor forgot-password flow state
  final _forgotPasswordEmailCtrl = TextEditingController();
  final _newPasswordCtrl = TextEditingController();
  final _confirmNewPasswordCtrl = TextEditingController();
  String? _resetOtp;          // OTP generated by backend (mock)
  String? _resetEmail;        // email the OTP was sent to
  String? _vendorLoginOtpPhone; // masked phone shown on vendor login OTP screen
  bool _pendingVendorRememberMe = false; // remember-me value pending OTP verification
  bool _pendingCustomerRememberMe = false; // remember-me value pending OTP verification
  String? _previousPassword;  // current password before reset (for same-password check)

  // Vendor register data â€” collected from onCreateAccountWithData
  Map<String, String>? _pendingVendorRegData;

  bool _isLoading = false;

  SriLankaProvince? _selectedProvince;
  SriLankaDistrict? _selectedDistrict;
  bool _isDetectingGps = false;
  double? _detectedLatitude;
  double? _detectedLongitude;
  // Vendor register pin â€” lifted so it survives SL â†” Intl page switches
  LatLng? _vendorPinPoint;
  bool _isHandlingBack = false;


  // Page order defines forward/back direction
  static const _pageOrder = [
    _FigmaAuthPage.customerLogin,
    _FigmaAuthPage.customerLoginOtp,
    _FigmaAuthPage.customerRegister,
    _FigmaAuthPage.customerRegisterOtp,
    _FigmaAuthPage.vendorLogin,
    _FigmaAuthPage.vendorLoginOtp,
    _FigmaAuthPage.vendorRegister,
    _FigmaAuthPage.vendorRegisterOtp,
    _FigmaAuthPage.vendorForgotPassword,
    _FigmaAuthPage.vendorForgotPasswordOtp,
    _FigmaAuthPage.vendorNewPassword,
  ];

  static Future<void> _hideNavBar() async {
    try {
      await const MethodChannel('com.speedmart.lk/system_ui').invokeMethod('hideNavBar');
    } catch (_) {}
  }

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    WidgetsBinding.instance.addPostFrameCallback((_) => _hideNavBar());
    _animCtrl = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 340),
    );
    // Build direction-aware animations once using a curved parent
    final curved = CurvedAnimation(parent: _animCtrl, curve: Curves.easeInOutCubic);
    _inSlide = _DirectionalTween(
      dirNotifier: _dirNotifier,
      inbound: true,
    ).animate(curved);
    _outSlide = _DirectionalTween(
      dirNotifier: _dirNotifier,
      inbound: false,
    ).animate(curved);
    _animCtrl.value = 1.0;
    _page = widget.role == FigmaAuthRole.customer
        ? _FigmaAuthPage.customerLogin
        : _FigmaAuthPage.vendorLogin;
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    _animCtrl.dispose();
    _loginPhoneCtrl.dispose();
    _vendorLoginEmailCtrl.dispose();
    _vendorLoginPasswordCtrl.dispose();
    _forgotPasswordEmailCtrl.dispose();
    _newPasswordCtrl.dispose();
    _confirmNewPasswordCtrl.dispose();
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) _hideNavBar();
  }

  @override
  Future<bool> didPopRoute() async {
    if (_isHandlingBack) return true;
    _isHandlingBack = true;
    try {
      final allow = await _onWillPop();
      if (allow && mounted) {
        SystemNavigator.pop();
      }
    } finally {
      _isHandlingBack = false;
    }
    return true;
  }



  void _go(_FigmaAuthPage page, {bool back = false, bool postFrame = false}) {
    if (!mounted) return;
    if (postFrame) {
      WidgetsBinding.instance.addPostFrameCallback((_) => _go(page, back: back));
      return;
    }
    FocusScope.of(context).unfocus();
    final currentIdx = _pageOrder.indexOf(_page);
    final nextIdx = _pageOrder.indexOf(page);
    final goingBack = back || (nextIdx < currentIdx);
    _dirNotifier.value = goingBack ? -1.0 : 1.0;
    setState(() {
      _prevPage = _page;
      _page = page;
    });
    _animCtrl.forward(from: 0.0);
  }

  // â”€â”€ Province picker â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  void _showProvincePicker() {
    showModalBottomSheet<SriLankaProvince>(
      context: context,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (_) => ListView(
        shrinkWrap: true,
        children: [
          const Padding(
            padding: EdgeInsets.fromLTRB(16, 16, 16, 8),
            child: Text('Select Province',
                style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
          ),
          ...SriLankaData.provinces.map((p) => ListTile(
                title: Text(p.name),
                selected: _selectedProvince?.id == p.id,
                onTap: () {
                  setState(() {
                    _selectedProvince = p;
                    _selectedDistrict = null;
                  });
                  Navigator.pop(context, p);
                },
              )),
          const SizedBox(height: 16),
        ],
      ),
    );
  }

  void _showDistrictPicker() {
    if (_selectedProvince == null) {
      _showToast('Please select a Province first');
      return;
    }
    showModalBottomSheet<SriLankaDistrict>(
      context: context,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (_) => ListView(
        shrinkWrap: true,
        children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 16, 16, 8),
            child: Text('Select District â€” ${_selectedProvince!.name}',
                style:
                    const TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
          ),
          ..._selectedProvince!.districts.map((d) => ListTile(
                title: Text(d.name),
                selected: _selectedDistrict?.id == d.id,
                onTap: () {
                  setState(() => _selectedDistrict = d);
                  Navigator.pop(context, d);
                },
              )),
          const SizedBox(height: 16),
        ],
      ),
    );
  }

  // â”€â”€ GPS auto-detect â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  Future<void> _autoDetectLocation() async {
    setState(() => _isDetectingGps = true);
    try {
      final position = await GpsLocationService().getCurrentPosition();
      final result = await ReverseGeocodingService().reverseGeocode(
        latitude: position.latitude,
        longitude: position.longitude,
      );
      if (!mounted) return;
      if (result.geocodingSucceeded &&
          result.province != null &&
          result.district != null) {
        final province = SriLankaData.provinceByName(result.province!);
        final district = SriLankaData.districtByName(result.district!);
        if (province != null && district != null) {
          setState(() {
            _selectedProvince = province;
            _selectedDistrict = district;
            _detectedLatitude = position.latitude;
            _detectedLongitude = position.longitude;
          });
          ref.read(customerRegistrationProvider.notifier).applyGpsLocation(
                province: province,
                district: district,
                approxArea: result.city ?? '',
                latitude: position.latitude,
                longitude: position.longitude,
                accuracy: result.accuracy,
                detectedAt: result.detectedAt ?? DateTime.now(),
              );
          if (mounted) {
            _showToast('Location detected: ${district.name}, ${province.name}');
          }
          return;
        }
      }
      if (mounted) _showToast('Could not detect location. Please select manually.');
    } on LocationException catch (e) {
      if (mounted) _showToast(e.message, isError: true);
    } catch (_) {
      if (mounted) _showToast('GPS unavailable. Please select manually.', isError: true);
    } finally {
      if (mounted) setState(() => _isDetectingGps = false);
    }
  }

  // â”€â”€ Customer register: validate & send OTP â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  Future<void> _onSriLankaCustomerCreateAccount(
      Map<String, String> data) async {
    final phone = (data['phone'] ?? '').trim();
    final fullName = (data['fullName'] ?? '').trim();
    final nic = (data['nic'] ?? '').trim();
    final email = (data['email'] ?? '').trim();
    final preciseAddress = (data['preciseAddress'] ?? '').trim();

    final nicErr = Validators.nic(nic);
    if (nicErr != null) { _showError(nicErr); return; }
    if (fullName.isEmpty) { _showError('Please enter your full name.'); return; }
    final phoneErr = SriLankaPhoneHelper.validateSriLankaMobile(phone);
    if (phoneErr != null) { _showError(phoneErr); return; }
    final emailErr = Validators.email(email);
    if (emailErr != null) { _showError(emailErr); return; }
    if (_detectedLatitude == null || _detectedLongitude == null) { _showError('Please pin your delivery location on the map.'); return; }
    if (_selectedProvince == null) { _showError('Please select your Province.'); return; }
    if (_selectedDistrict == null) { _showError('Please select your District.'); return; }
    if (preciseAddress.isEmpty) { _showError('Please enter your precise delivery address.'); return; }
    if (!await _checkOnline()) return;

    setState(() => _isLoading = true);
    try {
      await ref.read(authProvider.notifier).validateCustomerRegistrationData(
        phone: phone.trim(),
        email: (data['email'] ?? '').trim(),
        nic: nic.trim(),
      );

      final reg = ref.read(customerRegistrationProvider.notifier);
      reg.setMode(isLogin: false);
      reg.updateFullName(fullName.trim());
      reg.updatePhone(phone.trim());
      reg.updateNic(nic.trim());
      reg.updatePreciseAddress(preciseAddress.trim());
      reg.updateDeliveryNote(data['deliveryNote'] ?? '');
      reg.updateEmail(data['email'] ?? '');
      reg.updateProvince(_selectedProvince);
      reg.updateDistrict(_selectedDistrict);

      await reg.sendOtp();
      if (!mounted) return;
      final state = ref.read(customerRegistrationProvider);
      if (state.hasError) { _showError(state.error!); return; }
      _go(_FigmaAuthPage.customerRegisterOtp);
    } catch (e) {
      if (mounted) _showError(e.toString().replaceAll('Exception: ', ''));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  // â”€â”€ Customer login: send OTP â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  Future<void> _onSriLankaCustomerSendOtp(bool rememberMe) async {
    final phone = _loginPhoneCtrl.text.trim();
    if (phone.isEmpty) { _showError('Please enter your phone number.'); return; }
    if (!await _checkOnline()) return;

    setState(() => _isLoading = true);
    try {
      final wasRemembered = await StorageService.getCustomerRememberMe();
      final reg = ref.read(customerRegistrationProvider.notifier);
      reg.setMode(isLogin: true);
      reg.updatePhone(phone);

      if (rememberMe && wasRemembered) {
        final phoneDigits = phone.replaceAll(RegExp(r'[^0-9]'), '');
        final restored = await ref
            .read(authProvider.notifier)
            .restoreRememberedSession(
              role: UserRole.customer,
              matchesAccount: (UserModel user) {
                final savedDigits = user.phone.replaceAll(RegExp(r'[^0-9]'), '');
                return phoneDigits.isNotEmpty &&
                    savedDigits.isNotEmpty &&
                    (phoneDigits.endsWith(savedDigits.length > 9
                            ? savedDigits.substring(savedDigits.length - 9)
                            : savedDigits) ||
                        savedDigits.endsWith(phoneDigits.length > 9
                            ? phoneDigits.substring(phoneDigits.length - 9)
                            : phoneDigits));
              },
            );
        if (restored) {
          if (mounted) context.go(RouteNames.customerHome);
          return;
        }
      }

      _pendingCustomerRememberMe = rememberMe;
      await reg.sendOtp();
      if (!mounted) return;
      final state = ref.read(customerRegistrationProvider);
      if (state.hasError) { _showError(state.error!); return; }
      _go(_FigmaAuthPage.customerLoginOtp);
    } catch (e) {
      if (mounted) _showError(e.toString().replaceAll('Exception: ', ''));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  // â”€â”€ OTP success handlers â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  Future<void> _onCustomerLoginOtpSuccess(String otp, {bool rememberMe = false}) async {
    setState(() => _isLoading = true);
    try {
      if (otp.isNotEmpty) {
        // Firebase Phone Auth: verifyOtp signs the user into Firebase Auth directly
        final ok = await ref.read(customerRegistrationProvider.notifier).verifyOtp(otp);
        if (!mounted) return;
        if (!ok) {
          final errMsg = ref.read(customerRegistrationProvider).error ?? 'Incorrect OTP. Please try again.';
          _customerLoginOtpKey.currentState?.reportError(errMsg);
          _showError(errMsg);
          return;
        }
      }
      final regState = ref.read(customerRegistrationProvider);
      final contact = regState.data.primaryContact;
      await ref.read(authProvider.notifier).loginCustomerOtp(contact: contact);
      if (!mounted) return;
      await StorageService.saveCustomerRememberMe(rememberMe);
      if (!rememberMe) await StorageService.clearRememberedSession();
      context.go(RouteNames.customerHome);
    } catch (e) {
      if (mounted) _showError(e.toString().replaceAll('Exception: ', ''));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  Future<void> _onCustomerRegisterOtpSuccess(String otp) async {
    setState(() => _isLoading = true);
    try {
      final ok = await ref.read(customerRegistrationProvider.notifier).verifyOtp(otp);
      if (!mounted) return;
      if (!ok) {
        final errMsg = ref.read(customerRegistrationProvider).error ?? 'Incorrect OTP. Please try again.';
        _customerRegisterOtpKey.currentState?.reportError(errMsg);
        _showError(errMsg);
        return;
      }
      final regState = ref.read(customerRegistrationProvider);
      debugPrint('[FigmaAuth] Registering with lat=${regState.data.deliveryLatitude} lng=${regState.data.deliveryLongitude}');
      await ref.read(authProvider.notifier).register(
            fullName: regState.data.fullName,
            email: regState.data.email,
            phone: regState.data.phone,
            password: '',
            role: UserRole.customer,
            nic: regState.data.nic,
            verifiedPhone: true,
            detectedCountry: 'LK',
            detectionSource: 'app_default',
            deliveryProvince: _selectedProvince?.name ?? regState.data.province?.name,
            deliveryDistrict: _selectedDistrict?.name ?? regState.data.district?.name,
            deliveryApproxArea: regState.data.approxArea,
            deliveryPreciseAddress: regState.data.preciseAddress,
            deliveryNote: regState.data.deliveryNote,
            deliveryLatitude: regState.data.deliveryLatitude,
          deliveryLongitude: regState.data.deliveryLongitude,
          );
      if (!mounted) return;
      // Registration has already completed Firebase Phone OTP verification.
      // Treat the first signed-in session as opted in to remember me so logout
      // can offer the customer the choice to skip OTP next time.
      await StorageService.saveCustomerRememberMe(true);
      if (!mounted) return;
      final user = ref.read(currentUserProvider);
      if (user != null) {
        final defaultAddress = CustomerDeliveryAddress.fromUserFields(
          customerId: user.id,
          deliveryProvince: _selectedProvince?.name ?? regState.data.province?.name,
          deliveryDistrict: _selectedDistrict?.name ?? regState.data.district?.name,
          deliveryApproxArea: regState.data.approxArea,
          deliveryPreciseAddress: regState.data.preciseAddress,
          deliveryNote: regState.data.deliveryNote,
          accuracy: regState.data.deliveryAccuracy,
          detectedAt: regState.data.deliveryDetectedAt,
          deliveryLatitude: regState.data.deliveryLatitude,
          deliveryLongitude: regState.data.deliveryLongitude,
          isGpsDetected: regState.data.deliveryLatitude != null &&
              regState.data.deliveryLongitude != null,
          isManualOverride: false,
        );
        await ref.read(customerDeliveryAddressProvider.notifier).saveDefaultAddress(defaultAddress);
      }
      if (!mounted) return;
      context.go(RouteNames.customerHome);
    } catch (e) {
      if (mounted) _showError(e.toString().replaceAll('Exception: ', ''));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  // â”€â”€ OTP resend handlers â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  Future<void> _onCustomerResendOtp() async {
    await ref.read(customerRegistrationProvider.notifier).sendOtp();
    if (!mounted) return;
    final state = ref.read(customerRegistrationProvider);
    if (state.hasError) _showError(state.error!);
  }

  Future<void> _onSriLankaCustomerResendOtp() async {
    final phone = _loginPhoneCtrl.text.trim();
    if (phone.isEmpty) return;
    final reg = ref.read(customerRegistrationProvider.notifier);
    reg.updatePhone(phone);
    await reg.sendOtp();
    if (!mounted) return;
    final state = ref.read(customerRegistrationProvider);
    if (state.hasError) _showError(state.error!);
  }

  // â”€â”€ Vendor login â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  Future<void> _onVendorSignIn(bool rememberMe) async {
    final email = _vendorLoginEmailCtrl.text.trim();
    final password = _vendorLoginPasswordCtrl.text;
    if (email.isEmpty) { _showError('Please enter your email.'); return; }
    if (password.isEmpty) { _showError('Please enter your password.'); return; }
    if (!await _checkOnline()) return;

    setState(() => _isLoading = true);
    try {
      // Read the previously stored flag BEFORE this login
      final wasRemembered = await StorageService.getVendorRememberMe();

      final result = await ref.read(authProvider.notifier).verifyVendorCredentials(
        email: email,
        password: password,
      );
      if (!mounted) return;
      final authState = ref.read(authProvider);
      if (authState.hasError || result == null) {
        _showError(authState.error ?? 'Login failed.');
        return;
      }
      // Skip OTP only if vendor had Remember Me from a PREVIOUS session
      if (rememberMe && wasRemembered) {
        final restored = await ref
            .read(authProvider.notifier)
            .restoreRememberedSession(
              role: UserRole.vendor,
              matchesAccount: (user) =>
                  user.email.toLowerCase() == email.toLowerCase(),
            );
        if (restored) {
          if (mounted) context.go(RouteNames.vendorHome);
          return;
        }
      }
      {
        final reg = ref.read(customerRegistrationProvider.notifier);
        reg.setMode(isLogin: false);
        reg.updatePhone(result.phone);
        await reg.sendOtp();
        if (!mounted) return;
        final regState = ref.read(customerRegistrationProvider);
        if (regState.hasError) { _showError(regState.error!); return; }
        _vendorLoginOtpPhone = regState.maskedContact;
        _pendingVendorRememberMe = rememberMe;
        _go(_FigmaAuthPage.vendorLoginOtp);
      }
    } catch (e) {
      if (mounted) _showError(e.toString().replaceAll('Exception: ', ''));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  String _maskEmail(String email) {
    final at = email.indexOf('@');
    if (at <= 1) return email;
    final local = email.substring(0, at);
    final domain = email.substring(at);
    final visible = local.length > 3 ? local.substring(0, 3) : local[0];
    return '$visible***$domain';
  }

  // â”€â”€ Vendor register â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  Future<void> _onVendorCreateAccount(Map<String, String> data) async {
    final email = data['email'] ?? '';
    final fullName = data['fullName'] ?? '';
    final password = data['password'] ?? '';
    final confirmPassword = data['confirmPassword'] ?? '';
    final shopName = data['shopName'] ?? '';
    final categories = data['categories'] ?? '';

    if (fullName.trim().isEmpty) { _showError('Please enter your full name.'); return; }
    final emailErr = Validators.email(email.trim());
    if (emailErr != null) { _showError('Please enter a valid email.'); return; }
    if (password.length < 8) { _showError('Password must be at least 8 characters.'); return; }
    if (password != confirmPassword) { _showError('Passwords do not match.'); return; }
    if (shopName.trim().isEmpty) { _showError('Please enter your shop name.'); return; }
    if (categories.trim().isEmpty) { _showError('Please select at least one category.'); return; }
    final nic = (data['nic'] ?? '').trim().toUpperCase();
    if (nic.isNotEmpty) {
      final nicErr = Validators.nic(nic);
      if (nicErr != null) { _showError(nicErr); return; }
    }

    final lat = double.tryParse(data['latitude'] ?? '');
    final lng = double.tryParse(data['longitude'] ?? '');
    if (lat == null || lng == null) { _showError('Please pin your shop location on the map.'); return; }

    // Store form data and send OTP â€” registration happens after OTP verified
    _pendingVendorRegData = data;
    if (!await _checkOnline()) return;

    setState(() => _isLoading = true);
    try {
      final reg = ref.read(customerRegistrationProvider.notifier);
      reg.setMode(isLogin: false);
      // Vendor phone is a Sri Lanka mobile — ensure registration treats
      // this as an LK phone user so OTP is sent to the phone, not email.
      reg.setLkUser(true);

      final rawPhone = (data['phone'] ?? '').trim();
      debugPrint('[VendorRegister] raw phone input: "$rawPhone"');
      final normalized = SriLankaPhoneHelper.normalizeSriLankaPhoneForStorage(rawPhone);
      debugPrint('[VendorRegister] normalized for storage: "$normalized"');
      reg.updatePhone(rawPhone);

      await reg.sendOtp();
      if (!mounted) return;

      final regState = ref.read(customerRegistrationProvider);
      if (regState.hasError) {
        _showError(regState.error!);
        return;
      }

      _go(_FigmaAuthPage.vendorRegisterOtp);
    } catch (e) {
      if (mounted) _showError(e.toString().replaceAll('Exception: ', ''));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  Future<void> _onVendorRegisterOtpSuccess(String otp) async {
    final data = _pendingVendorRegData;
    if (data == null) { _showError('Session expired. Please try again.'); return; }

    final ok = await ref.read(customerRegistrationProvider.notifier).verifyOtp(otp);
    if (!mounted) return;
    if (!ok) {
      final errMsg = ref.read(customerRegistrationProvider).error ?? 'Incorrect OTP. Please try again.';
      _vendorRegisterOtpKey.currentState?.reportError(errMsg);
      _showError(errMsg);
      return;
    }

    setState(() => _isLoading = true);
    try {
      final email = data['email'] ?? '';
      final shopName = data['shopName'] ?? '';
      final categories = data['categories'] ?? '';
      final lat = double.tryParse(data['latitude'] ?? '')!;
      final lng = double.tryParse(data['longitude'] ?? '')!;
      final nic = (data['nic'] ?? '').trim().toUpperCase();

      await ref.read(authProvider.notifier).register(
        fullName: data['fullName']!.trim(),
        email: email.trim(),
        phone: data['phone'] ?? '',
        password: data['password']!,
        role: UserRole.vendor,
        nic: nic.isNotEmpty ? nic : null,
        businessName: shopName.trim(),
        categories: categories.isNotEmpty ? categories.split(',') : null,
        shopName: shopName.trim(),
        shopAddress: data['shopAddress'] ?? '',
        shopProvince: data['province']?.isNotEmpty == true ? data['province'] : null,
        shopDistrict: data['district']?.isNotEmpty == true ? data['district'] : null,
        shopLatitude: lat,
        shopLongitude: lng,
        shopLocationSource: 'map_pin',
        businessRegistrationNumber: data['businessRegNo']?.isNotEmpty == true ? data['businessRegNo'] : null,
        detectedCountry: 'LK',
        detectionSource: 'app_default',
        verifiedPhone: true,
        verifiedEmail: false,
        shopLocationAccuracyMeters: 0,
        shopLocationDetectedAt: DateTime.now(),
      );
      if (!mounted) return;
      final authState = ref.read(authProvider);
      if (authState.hasError) {
        _showError(authState.error!);
      } else if (authState.isAuthenticated) {
        _pendingVendorRegData = null;
        context.go(RouteNames.vendorHome);
      }
    } catch (e) {
      if (mounted) _showError(e.toString().replaceAll('Exception: ', ''));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  Future<void> _onVendorRegisterResendOtp() async {
    final phone = _pendingVendorRegData?['phone'] ?? '';
    if (phone.isEmpty) return;
    final reg = ref.read(customerRegistrationProvider.notifier);
    reg.updatePhone(phone);
    await reg.sendOtp();
    if (!mounted) return;
    final state = ref.read(customerRegistrationProvider);
    if (state.hasError) _showError(state.error!);
  }

  // â”€â”€ Vendor forgot-password handlers â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  Future<void> _onVendorForgotPasswordSendCode(_FigmaAuthPage otpPage) async {
    final email = _forgotPasswordEmailCtrl.text.trim();
    if (email.isEmpty || !email.contains('@')) {
      _showError('Please enter a valid email address.');
      return;
    }
    setState(() => _isLoading = true);
    try {
      final otp = await ref.read(authProvider.notifier).generateResetOtp(email);
      if (!mounted) return;
      _resetOtp = otp;
      _resetEmail = email;
      _previousPassword = await ref.read(authProvider.notifier).getVendorPassword(email);
      _go(otpPage);
    } catch (e) {
      if (mounted) _showError(e.toString().replaceAll('Exception: ', ''));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  void _onVendorForgotPasswordVerifyOtp(
      String enteredOtp, _FigmaAuthPage newPasswordPage) {
    if (_resetOtp == null || enteredOtp != _resetOtp) {
      _showError('Invalid OTP. Please try again.');
      return;
    }
    _go(newPasswordPage);
  }

  Future<void> _onVendorUpdatePassword(
      TextEditingController passwordCtrl,
      TextEditingController confirmCtrl,
      _FigmaAuthPage loginPage) async {
    final password = passwordCtrl.text;
    final confirm = confirmCtrl.text;
    if (password.length < 8) {
      _showError('Password must be at least 8 characters.');
      return;
    }
    if (password != confirm) {
      _showError('Passwords do not match.');
      return;
    }
    if (_resetEmail == null) {
      _showError('Session expired. Please restart the reset process.');
      return;
    }
    setState(() => _isLoading = true);
    try {
      await ref.read(authProvider.notifier).resetPassword(
            email: _resetEmail!,
            newPassword: password,
          );
      if (!mounted) return;
      final authState = ref.read(authProvider);
      if (authState.hasError) {
        _showError(authState.error!);
        return;
      }
      _resetOtp = null;
      _resetEmail = null;
      _previousPassword = null;
      _forgotPasswordEmailCtrl.clear();
      _newPasswordCtrl.clear();
      _confirmNewPasswordCtrl.clear();
      _showToast('Password updated successfully!');
      _go(loginPage);
    } catch (e) {
      if (mounted) _showError(e.toString().replaceAll('Exception: ', ''));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  Future<void> _onVendorOtpSuccess(String otp, {bool rememberMe = false}) async {
    final email = _vendorLoginEmailCtrl.text.trim();
    setState(() => _isLoading = true);
    try {
      if (otp.isNotEmpty) {
        final ok = await ref.read(customerRegistrationProvider.notifier).verifyOtp(otp);
        if (!mounted) return;
        if (!ok) {
          final errMsg = ref.read(customerRegistrationProvider).error ?? 'Incorrect OTP. Please try again.';
          _vendorLoginOtpKey.currentState?.reportError(errMsg);
          _showError(errMsg);
          return;
        }
      }
      
      await ref.read(authProvider.notifier).loginVendorAfterOtp(
            email: email,
            password: _vendorLoginPasswordCtrl.text,
          );
      if (!mounted) return;
      final authState = ref.read(authProvider);
      if (authState.hasError) {
        _showError(authState.error!);
        return;
      }
      await StorageService.saveVendorRememberMe(rememberMe);
      context.go(RouteNames.vendorHome);
    } catch (e) {
      if (mounted) _showError(e.toString().replaceAll('Exception: ', ''));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  void _showToast(String message, {bool isError = false}) {
    if (!mounted) return;
    final overlay = Overlay.of(context);
    late OverlayEntry entry;
    entry = OverlayEntry(
      builder: (_) => _ToastOverlay(
        message: message,
        isError: isError,
        onClose: () => entry.remove(),
      ),
    );
    overlay.insert(entry);
    Future.delayed(const Duration(seconds: 4), () {
      if (entry.mounted) entry.remove();
    });
  }

  void _showError(String message) => _showToast(message, isError: true);

  Future<bool> _checkOnline() async {
    final online = await ConnectivityService.instance.isOnline();
    if (!online && mounted) _showError('No network. Check your connection and try again.');
    return online;
  }

  // â”€â”€ Build â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  // Pages that contain heavy maps â€” kept permanently mounted via Offstage
  static const _persistentPages = {_FigmaAuthPage.vendorRegister};

  // Returns the page to go back to, or null if this is a root login page
  _FigmaAuthPage? _backTarget() {
    switch (_page) {
      case _FigmaAuthPage.customerRegister:
      case _FigmaAuthPage.customerLoginOtp:
        return _FigmaAuthPage.customerLogin;
      case _FigmaAuthPage.customerRegisterOtp:
        return _FigmaAuthPage.customerRegister;
      case _FigmaAuthPage.vendorRegister:
      case _FigmaAuthPage.vendorLoginOtp:
      case _FigmaAuthPage.vendorForgotPassword:
        return _FigmaAuthPage.vendorLogin;
      case _FigmaAuthPage.vendorRegisterOtp:
        return _FigmaAuthPage.vendorRegister;
      case _FigmaAuthPage.vendorForgotPasswordOtp:
        return _FigmaAuthPage.vendorForgotPassword;
      case _FigmaAuthPage.vendorNewPassword:
        return _FigmaAuthPage.vendorForgotPasswordOtp;
      // Root login pages — no internal back target
      case _FigmaAuthPage.customerLogin:
      case _FigmaAuthPage.vendorLogin:
        return null;
    }
  }

  Future<bool> _onWillPop() async {
    final target = _backTarget();
    if (target != null) {
      _go(target, back: true);
      return false;
    }
    // Root login page — show exit confirmation
    final shouldExit = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('Exit App?'),
        content: const Text('Are you sure you want to exit?'),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(ctx).pop(false),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () => Navigator.of(ctx).pop(true),
            child: const Text('Exit'),
          ),
        ],
      ),
    );
    return shouldExit ?? false;
  }

  @override
  Widget build(BuildContext context) {
    final slvReg = _buildPageFor(_FigmaAuthPage.vendorRegister);

    return PopScope(
      canPop: false,
      onPopInvokedWithResult: (didPop, _) {
        if (didPop || _isHandlingBack) return;
        _isHandlingBack = true;
        WidgetsBinding.instance.addPostFrameCallback((_) async {
          try {
            if (!mounted) return;
            final allow = await _onWillPop();
            if (allow && mounted) {
              SystemNavigator.pop();
            }
          } finally {
            _isHandlingBack = false;
          }
        });
      },
      child: Scaffold(
        backgroundColor: const Color(0xFF0A1628),
        body: AnimatedBuilder(
          animation: _animCtrl,
          builder: (context, _) {
            final showPrev = _prevPage != null && _animCtrl.value < 1.0;

            Widget buildSlide(_FigmaAuthPage page, bool isInbound) {
              final child = page == _FigmaAuthPage.vendorRegister
                  ? slvReg
                  : _buildPageFor(page);
              return SlideTransition(
                position: isInbound ? _inSlide : _outSlide,
                child: RepaintBoundary(child: child),
              );
            }

            return Stack(
              children: [
                if (_page != _FigmaAuthPage.vendorRegister &&
                    !(_prevPage == _FigmaAuthPage.vendorRegister && showPrev))
                  Offstage(child: TickerMode(enabled: false, child: slvReg)),
                if (showPrev) buildSlide(_prevPage!, false),
                buildSlide(_page, true),
                if (_isLoading) const Positioned.fill(child: AuthLoadingOverlay()),
              ],
            );
          },
        ),
      ),
    );
  }

  Widget _buildPageFor(_FigmaAuthPage page) {
    switch (page) {
      case _FigmaAuthPage.customerLogin:
        return SrilankacustomerloginWidget(
          phoneController: _loginPhoneCtrl,
          isLoading: _isLoading,
          onSendOtp: _isLoading ? null : _onSriLankaCustomerSendOtp,
          onRegister: () => _go(_FigmaAuthPage.customerRegister),
          onVendorLogin: () => _go(_FigmaAuthPage.vendorLogin),
        );

      case _FigmaAuthPage.customerLoginOtp:
        return SrilankacustomerloginotpWidget(
          key: _customerLoginOtpKey,
          onVerifyOtp: (otp) => _onCustomerLoginOtpSuccess(otp, rememberMe: _pendingCustomerRememberMe),
          onBack: () => _go(_FigmaAuthPage.customerLogin, back: true),
          maskedPhone: ref.read(customerRegistrationProvider).maskedContact ?? '',
          onResend: _onSriLankaCustomerResendOtp,
        );

      case _FigmaAuthPage.customerRegister:
        return SrilankacustomerregisteraccountWidget(
          onBack: () => _go(_FigmaAuthPage.customerLogin, back: true),
          onSignIn: () => _go(_FigmaAuthPage.customerLogin, back: true),
          onProvinceTap: _showProvincePicker,
          onDistrictTap: _showDistrictPicker,
          onUseCurrentLocation: _isDetectingGps ? null : _autoDetectLocation,
          isDetectingLocation: _isDetectingGps,
          onCreateAccountWithData: _onSriLankaCustomerCreateAccount,
          selectedProvince: _selectedProvince?.name,
          selectedDistrict: _selectedDistrict?.name,
          initialLatitude: _detectedLatitude,
          initialLongitude: _detectedLongitude,
          onLocationPinChanged: (lat, lng) => setState(() {
            _detectedLatitude = lat;
            _detectedLongitude = lng;
          }),
        );

      case _FigmaAuthPage.customerRegisterOtp:
        return SrilankacustomerregistrationotpWidget(
          key: _customerRegisterOtpKey,
          onVerifyOtp: _onCustomerRegisterOtpSuccess,
          onBack: () => _go(_FigmaAuthPage.customerRegister, back: true),
          maskedPhone: ref.read(customerRegistrationProvider).maskedContact ?? '',
          onResend: _onCustomerResendOtp,
        );

      case _FigmaAuthPage.vendorLogin:
        return SrilankavendorloginWidget(
          emailController: _vendorLoginEmailCtrl,
          passwordController: _vendorLoginPasswordCtrl,
          onSignIn: _isLoading ? null : _onVendorSignIn,
          isLoading: _isLoading,
          onRegister: () => _go(_FigmaAuthPage.vendorRegister),
          onCustomerLogin: () => _go(_FigmaAuthPage.customerLogin),
          onForgotPassword: () => _go(_FigmaAuthPage.vendorForgotPassword),
        );

      case _FigmaAuthPage.vendorLoginOtp:
        return SrilankavendorloginotpWidget(
          key: _vendorLoginOtpKey,
          onVerifyOtp: (otp) => _onVendorOtpSuccess(otp, rememberMe: _pendingVendorRememberMe),
          maskedPhone: _vendorLoginOtpPhone ?? '',
          onBack: () => _go(_FigmaAuthPage.vendorLogin, back: true),
        );

      case _FigmaAuthPage.vendorRegister:
        return SrilankavendorregistrationWidget(
          onBack: () => _go(_FigmaAuthPage.vendorLogin, back: true),
          onSignIn: () => _go(_FigmaAuthPage.vendorLogin, back: true),
          onCreateAccountWithData: _isLoading ? null : _onVendorCreateAccount,
          onProvinceTap: _showProvincePicker,
          onDistrictTap: _showDistrictPicker,
          onUseCurrentLocation: _isDetectingGps ? null : _autoDetectLocation,
          isDetectingLocation: _isDetectingGps,
          selectedProvince: _selectedProvince?.name,
          selectedDistrict: _selectedDistrict?.name,
          initialLatitude: _detectedLatitude,
          initialLongitude: _detectedLongitude,
          externalPinPoint: _vendorPinPoint,
          isLoading: _isLoading,
          onLocationPinChanged: (lat, lng) => setState(() {
            _detectedLatitude = lat;
            _detectedLongitude = lng;
            _vendorPinPoint = LatLng(lat, lng);
          }),
        );

      case _FigmaAuthPage.vendorRegisterOtp:
        return SrilankavendorregistrationotpWidget(
          key: _vendorRegisterOtpKey,
          onVerifyOtp: _onVendorRegisterOtpSuccess,
          onResend: _onVendorRegisterResendOtp,
          maskedPhone: ref.read(customerRegistrationProvider).maskedContact ?? '',
          onBack: () => _go(_FigmaAuthPage.vendorRegister, back: true),
        );

      case _FigmaAuthPage.vendorForgotPassword:
        return SrilankavendorforgetpasswordWidget(
          emailController: _forgotPasswordEmailCtrl,
          isLoading: _isLoading,
          onBack: () => _go(_FigmaAuthPage.vendorLogin, back: true),
          onSignIn: () => _go(_FigmaAuthPage.vendorLogin, back: true),
          onSendResetCode: _isLoading
              ? null
              : () => _onVendorForgotPasswordSendCode(_FigmaAuthPage.vendorForgotPasswordOtp),
        );

      case _FigmaAuthPage.vendorForgotPasswordOtp:
        return SrilankavendorforgetpasswordotpWidget(
          onSignIn: () => _go(_FigmaAuthPage.vendorLogin, back: true),
          onBack: () => _go(_FigmaAuthPage.vendorForgotPassword, back: true),
          onResendCode: () => _onVendorForgotPasswordSendCode(_FigmaAuthPage.vendorForgotPasswordOtp),
          onVerifyCode: (otp) => _onVendorForgotPasswordVerifyOtp(otp, _FigmaAuthPage.vendorNewPassword),
        );

      case _FigmaAuthPage.vendorNewPassword:
        return NewpasswordupdatesrilankavendorWidget(
          passwordController: _newPasswordCtrl,
          confirmPasswordController: _confirmNewPasswordCtrl,
          isLoading: _isLoading,
          previousPassword: _previousPassword,
          onBack: () => _go(_FigmaAuthPage.vendorForgotPasswordOtp, back: true),
          onUpdatePassword: _isLoading
              ? null
              : () => _onVendorUpdatePassword(
                    _newPasswordCtrl,
                    _confirmNewPasswordCtrl,
                    _FigmaAuthPage.vendorLogin,
                  ),
        );
    }
  }
}

class _DirectionalTween extends Animatable<Offset> {
  final ValueNotifier<double> dirNotifier;
  final bool inbound;
  const _DirectionalTween({required this.dirNotifier, required this.inbound});

  @override
  Offset transform(double t) {
    final dir = dirNotifier.value; // +1 forward, -1 back
    if (inbound) {
      // starts off-screen in the direction of travel, slides to zero
      return Offset(dir * (1.0 - t), 0);
    } else {
      // starts at zero, slides off-screen opposite to travel
      return Offset(-dir * t, 0);
    }
  }
}

class _ToastOverlay extends StatefulWidget {
  final String message;
  final bool isError;
  final VoidCallback onClose;

  const _ToastOverlay({
    required this.message,
    required this.isError,
    required this.onClose,
  });

  @override
  State<_ToastOverlay> createState() => _ToastOverlayState();
}

class _ToastOverlayState extends State<_ToastOverlay>
    with SingleTickerProviderStateMixin {
  late final AnimationController _ctrl;
  late final Animation<double> _fade;
  late final Animation<Offset> _slide;

  @override
  void initState() {
    super.initState();
    _ctrl = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 280),
    );
    _fade = CurvedAnimation(parent: _ctrl, curve: Curves.easeOut);
    _slide = Tween<Offset>(
      begin: const Offset(0, -0.5),
      end: Offset.zero,
    ).animate(CurvedAnimation(parent: _ctrl, curve: Curves.easeOutCubic));
    _ctrl.forward();
  }

  @override
  void dispose() {
    _ctrl.dispose();
    super.dispose();
  }

  // build is below

  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: TextDirection.ltr,
      child: SizedBox.expand(
        child: Align(
          alignment: Alignment.topCenter,
          child: Padding(
            padding: const EdgeInsets.fromLTRB(20, 52, 20, 0),
            child: FadeTransition(
              opacity: _fade,
              child: SlideTransition(
                position: _slide,
                child: Material(
                  color: Colors.transparent,
                  child: Container(
                    padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
                    decoration: BoxDecoration(
                      color: widget.isError ? const Color(0xFFB71C1C) : const Color(0xFF1B5E20),
                      borderRadius: BorderRadius.circular(12),
                      boxShadow: const [
                        BoxShadow(
                          color: Colors.black26,
                          blurRadius: 10,
                          offset: Offset(0, 4),
                        ),
                      ],
                    ),
                    child: Row(
                      children: [
                        Icon(
                          widget.isError ? Icons.error_outline_rounded : Icons.check_circle_outline_rounded,
                          color: Colors.white,
                          size: 20,
                        ),
                        const SizedBox(width: 10),
                        Expanded(
                          child: Text(
                            widget.message,
                            style: const TextStyle(
                              color: Colors.white,
                              fontFamily: 'Inter',
                              fontSize: 13.5,
                              fontWeight: FontWeight.w600,
                              height: 1.3,
                            ),
                          ),
                        ),
                        const SizedBox(width: 8),
                        GestureDetector(
                          onTap: widget.onClose,
                          child: const Icon(Icons.close_rounded, color: Colors.white70, size: 18),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

