import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:latlong2/latlong.dart';

import '../features/auth/providers/auth_provider.dart';
import '../features/auth/customer_registration/providers/customer_registration_provider.dart';
import '../features/auth/customer_registration/services/country_detection_service.dart';
import '../features/customer/delivery_address/models/customer_delivery_address.dart';
import '../features/customer/delivery_address/providers/customer_delivery_address_provider.dart';
import '../features/location/data/sri_lanka_data.dart';
import '../features/location/models/sri_lanka_province.dart';
import '../features/location/models/sri_lanka_district.dart';
import '../features/location/services/gps_location_service.dart';
import '../features/location/services/reverse_geocoding_service.dart';
import '../shared/models/user_role.dart';
import '../core/routes/route_names.dart';
import '../core/storage/storage_service.dart';
import '../widgets/auth/speedmart_country_switch_popup.dart';

import 'sri_lanka_customer_login_figma.dart';
import 'sri_lanka_customer_login_otp_figma.dart';
import 'sri_lanka_customer_register_figma.dart';
import 'sri_lanka_customer_register_otp_figma.dart';

import 'international_customer_login_figma.dart';
import 'international_customer_login_otp_figma.dart';
import 'international_customer_register_figma.dart';
import 'international_customer_register_otp_figma.dart';

import 'sri_lanka_vendor_login_figma.dart';
import 'sri_lanka_vendor_login_otp_figma.dart';
import 'sri_lanka_vendor_register_figma.dart';
import 'sri_lanka_vendor_register_otp_figma.dart';

import 'sri_lanka_vendor_forget_password_figma.dart';
import 'sri_lanka_vendor_forget_password_otp_figma.dart';
import 'new_password_update_sri_lanka_vendor_figma.dart';

import 'international_vendor_login_figma.dart';
import 'international_vendor_login_otp_figma.dart';
import 'international_vendor_register_figma.dart';
import 'international_vendor_register_otp_figma.dart';

import 'international_vendor_forget_password_figma.dart';
import 'international_vendor_forget_password_otp_figma.dart';
import 'new_password_update_international_vendor_figma.dart';

enum FigmaAuthRole { customer, vendor }

enum _FigmaAuthPage {
  sriLankaCustomerLogin,
  internationalCustomerLogin,
  sriLankaCustomerRegister,
  internationalCustomerRegister,
  sriLankaCustomerLoginOtp,
  internationalCustomerLoginOtp,
  sriLankaCustomerRegisterOtp,
  internationalCustomerRegisterOtp,
  sriLankaVendorLogin,
  internationalVendorLogin,
  sriLankaVendorRegister,
  internationalVendorRegister,
  sriLankaVendorLoginOtp,
  internationalVendorLoginOtp,
  sriLankaVendorRegisterOtp,
  internationalVendorRegisterOtp,
  sriLankaVendorForgotPassword,
  internationalVendorForgotPassword,
  sriLankaVendorForgotPasswordOtp,
  internationalVendorForgotPasswordOtp,
  sriLankaVendorNewPassword,
  internationalVendorNewPassword,
}

class FigmaAuthFlow extends ConsumerStatefulWidget {
  const FigmaAuthFlow({super.key, required this.role});
  final FigmaAuthRole role;

  @override
  ConsumerState<FigmaAuthFlow> createState() => _FigmaAuthFlowState();
}

class _FigmaAuthFlowState extends ConsumerState<FigmaAuthFlow>
    with SingleTickerProviderStateMixin {
  bool _detecting = true;
  _FigmaAuthPage _page = _FigmaAuthPage.sriLankaCustomerLogin;
  _FigmaAuthPage? _prevPage;
  bool _detectedIsLk = true; // result from CountryDetectionService
  // Once user confirms a switch away from detected country, remember it so
  // subsequent taps in that same direction skip the popup.
  bool _hasConfirmedAwayFromDetected = false;
  bool _switchInProgress = false;

  late final AnimationController _animCtrl;
  late final Animation<Offset> _inSlide;
  late final Animation<Offset> _outSlide;
  // direction multiplier: +1 = forward, -1 = back
  final _dirNotifier = ValueNotifier<double>(1.0);

  // ── Registration form state ───────────────────────────────────────────────
  // Controllers are held here so they survive page transitions within the flow
  final _regPhoneCtrl = TextEditingController();
  final _regEmailCtrl = TextEditingController();

  // Login contact (phone for LK, email for intl)
  final _loginPhoneCtrl = TextEditingController();
  final _loginEmailCtrl = TextEditingController();

  // Vendor login controllers — passed into figma login widgets
  final _vendorLoginEmailCtrl = TextEditingController();
  final _vendorLoginPasswordCtrl = TextEditingController();

  // Vendor forgot-password flow state
  final _forgotPasswordEmailCtrl = TextEditingController();
  final _newPasswordCtrl = TextEditingController();
  final _confirmNewPasswordCtrl = TextEditingController();
  String? _resetOtp;          // OTP generated by backend (mock)
  String? _resetEmail;        // email the OTP was sent to
  String? _vendorLoginOtpEmail; // masked email shown on vendor login OTP screen
  String? _previousPassword;  // current password before reset (for same-password check)

  // Vendor register data — collected from onCreateAccountWithData
  Map<String, String>? _pendingVendorRegData;

  bool _isVendorLoading = false;

  SriLankaProvince? _selectedProvince;
  SriLankaDistrict? _selectedDistrict;
  bool _isDetectingGps = false;
  double? _detectedLatitude;
  double? _detectedLongitude;
  // Vendor register pin — lifted so it survives SL ↔ Intl page switches
  LatLng? _vendorPinPoint;


  Future<void> _detectCountry() async {
    try {
      final result = await CountryDetectionService().detect();
      if (!mounted) return;
      setState(() {
        _detecting = false;
        _detectedIsLk = result.isLkUser;
        _page = _initialPage(isLk: result.isLkUser);
      });
    } catch (_) {
      if (!mounted) return;
      setState(() {
        _detecting = false;
        _detectedIsLk = true;
        _page = _initialPage(isLk: true);
      });
    }
  }

  _FigmaAuthPage _initialPage({required bool isLk}) {
    if (widget.role == FigmaAuthRole.customer) {
      return isLk
          ? _FigmaAuthPage.sriLankaCustomerLogin
          : _FigmaAuthPage.internationalCustomerLogin;
    } else {
      return isLk
          ? _FigmaAuthPage.sriLankaVendorLogin
          : _FigmaAuthPage.internationalVendorLogin;
    }
  }

  /// Returns true if the current page is in the Sri Lanka flow.
  bool get _isCurrentlyLk {
    const lkPages = {
      _FigmaAuthPage.sriLankaCustomerLogin,
      _FigmaAuthPage.sriLankaCustomerRegister,
      _FigmaAuthPage.sriLankaCustomerLoginOtp,
      _FigmaAuthPage.sriLankaCustomerRegisterOtp,
      _FigmaAuthPage.sriLankaVendorLogin,
      _FigmaAuthPage.sriLankaVendorRegister,
      _FigmaAuthPage.sriLankaVendorLoginOtp,
      _FigmaAuthPage.sriLankaVendorRegisterOtp,
      _FigmaAuthPage.sriLankaVendorForgotPassword,
      _FigmaAuthPage.sriLankaVendorForgotPasswordOtp,
      _FigmaAuthPage.sriLankaVendorNewPassword,
    };
    return lkPages.contains(_page);
  }

  /// Handles country switch tap with popup logic:
  /// - Switching back to detected country → switch directly, reset confirmation
  /// - Switching away from detected country for the first time → show popup
  /// - Switching away from detected country again (already confirmed) → switch directly
  Future<void> _onCountrySwitch(_FigmaAuthPage targetPage) async {
    if (_switchInProgress) return;
    _switchInProgress = true;
    try {
      final targetIsLk = !_isCurrentlyLk;
      final isGoingBackToDetected = targetIsLk == _detectedIsLk;

      if (isGoingBackToDetected || _hasConfirmedAwayFromDetected) {
        if (isGoingBackToDetected) _hasConfirmedAwayFromDetected = false;
        _go(targetPage);
        return;
      }

      final isLoginPage = _page == _FigmaAuthPage.sriLankaCustomerLogin ||
          _page == _FigmaAuthPage.internationalCustomerLogin ||
          _page == _FigmaAuthPage.sriLankaVendorLogin ||
          _page == _FigmaAuthPage.internationalVendorLogin;
      final flow = isLoginPage ? SpeedmartAuthFlow.login : SpeedmartAuthFlow.register;
      final role = widget.role == FigmaAuthRole.customer
          ? SpeedmartUserRole.customer
          : SpeedmartUserRole.vendor;

      final confirmed = await showSpeedmartCountrySwitchPopup(
        context: context,
        targetMode: targetIsLk
            ? SpeedmartCountryMode.sriLanka
            : SpeedmartCountryMode.international,
        flow: flow,
        role: role,
      );
      if (confirmed == true && mounted) {
        _hasConfirmedAwayFromDetected = true;
        _go(targetPage);
      }
    } finally {
      _switchInProgress = false;
    }
  }

  // Page order defines forward/back direction
  static const _pageOrder = [
    _FigmaAuthPage.sriLankaCustomerLogin,
    _FigmaAuthPage.internationalCustomerLogin,
    _FigmaAuthPage.sriLankaCustomerRegister,
    _FigmaAuthPage.internationalCustomerRegister,
    _FigmaAuthPage.sriLankaCustomerLoginOtp,
    _FigmaAuthPage.internationalCustomerLoginOtp,
    _FigmaAuthPage.sriLankaCustomerRegisterOtp,
    _FigmaAuthPage.internationalCustomerRegisterOtp,
    _FigmaAuthPage.sriLankaVendorLogin,
    _FigmaAuthPage.internationalVendorLogin,
    _FigmaAuthPage.sriLankaVendorRegister,
    _FigmaAuthPage.internationalVendorRegister,
    _FigmaAuthPage.sriLankaVendorLoginOtp,
    _FigmaAuthPage.internationalVendorLoginOtp,
    _FigmaAuthPage.sriLankaVendorRegisterOtp,
    _FigmaAuthPage.internationalVendorRegisterOtp,
    _FigmaAuthPage.sriLankaVendorForgotPassword,
    _FigmaAuthPage.internationalVendorForgotPassword,
    _FigmaAuthPage.sriLankaVendorForgotPasswordOtp,
    _FigmaAuthPage.internationalVendorForgotPasswordOtp,
    _FigmaAuthPage.sriLankaVendorNewPassword,
    _FigmaAuthPage.internationalVendorNewPassword,
  ];

  @override
  void initState() {
    super.initState();
    _animCtrl = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 340),
    );
    // Build direction-aware animations once using a curved parent
    final curved = CurvedAnimation(parent: _animCtrl, curve: Curves.easeInOutCubic);
    _inSlide = _DirectionalTween(
      dirNotifier: _dirNotifier,
      inbound: true,
    ).animate(curved);
    _outSlide = _DirectionalTween(
      dirNotifier: _dirNotifier,
      inbound: false,
    ).animate(curved);
    _animCtrl.value = 1.0;
    _detectCountry();
  }

  @override
  void dispose() {
    _animCtrl.dispose();
    _regPhoneCtrl.dispose();
    _regEmailCtrl.dispose();
    _loginPhoneCtrl.dispose();
    _loginEmailCtrl.dispose();
    _vendorLoginEmailCtrl.dispose();
    _vendorLoginPasswordCtrl.dispose();
    _forgotPasswordEmailCtrl.dispose();
    _newPasswordCtrl.dispose();
    _confirmNewPasswordCtrl.dispose();
    super.dispose();
  }



  void _go(_FigmaAuthPage page, {bool back = false, bool postFrame = false}) {
    if (!mounted) return;
    if (postFrame) {
      WidgetsBinding.instance.addPostFrameCallback((_) => _go(page, back: back));
      return;
    }
    FocusScope.of(context).unfocus();
    final currentIdx = _pageOrder.indexOf(_page);
    final nextIdx = _pageOrder.indexOf(page);
    final goingBack = back || (nextIdx < currentIdx);
    _dirNotifier.value = goingBack ? -1.0 : 1.0;
    setState(() {
      _prevPage = _page;
      _page = page;
    });
    _animCtrl.forward(from: 0.0);
  }

  // ── Province picker ───────────────────────────────────────────────────────

  void _showProvincePicker() {
    showModalBottomSheet<SriLankaProvince>(
      context: context,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (_) => ListView(
        shrinkWrap: true,
        children: [
          const Padding(
            padding: EdgeInsets.fromLTRB(16, 16, 16, 8),
            child: Text('Select Province',
                style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
          ),
          ...SriLankaData.provinces.map((p) => ListTile(
                title: Text(p.name),
                selected: _selectedProvince?.id == p.id,
                onTap: () {
                  setState(() {
                    _selectedProvince = p;
                    _selectedDistrict = null;
                  });
                  Navigator.pop(context, p);
                },
              )),
          const SizedBox(height: 16),
        ],
      ),
    );
  }

  void _showDistrictPicker() {
    if (_selectedProvince == null) {
      _showToast('Please select a Province first');
      return;
    }
    showModalBottomSheet<SriLankaDistrict>(
      context: context,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (_) => ListView(
        shrinkWrap: true,
        children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 16, 16, 8),
            child: Text('Select District — ${_selectedProvince!.name}',
                style:
                    const TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
          ),
          ..._selectedProvince!.districts.map((d) => ListTile(
                title: Text(d.name),
                selected: _selectedDistrict?.id == d.id,
                onTap: () {
                  setState(() => _selectedDistrict = d);
                  Navigator.pop(context, d);
                },
              )),
          const SizedBox(height: 16),
        ],
      ),
    );
  }

  // ── GPS auto-detect ───────────────────────────────────────────────────────

  Future<void> _autoDetectLocation() async {
    setState(() => _isDetectingGps = true);
    try {
      final position = await GpsLocationService().getCurrentPosition();
      final result = await ReverseGeocodingService().reverseGeocode(
        latitude: position.latitude,
        longitude: position.longitude,
      );
      if (!mounted) return;
      if (result.geocodingSucceeded &&
          result.province != null &&
          result.district != null) {
        final province = SriLankaData.provinceByName(result.province!);
        final district = SriLankaData.districtByName(result.district!);
        if (province != null && district != null) {
          setState(() {
            _selectedProvince = province;
            _selectedDistrict = district;
            _detectedLatitude = position.latitude;
            _detectedLongitude = position.longitude;
          });
          ref.read(customerRegistrationProvider.notifier).applyGpsLocation(
                province: province,
                district: district,
                approxArea: result.city ?? '',
              );
          if (mounted) {
            _showToast('Location detected: ${district.name}, ${province.name}');
          }
          return;
        }
      }
      if (mounted) _showToast('Could not detect location. Please select manually.');
    } on LocationException catch (e) {
      if (mounted) _showToast(e.message, isError: true);
    } catch (_) {
      if (mounted) _showToast('GPS unavailable. Please select manually.', isError: true);
    } finally {
      if (mounted) setState(() => _isDetectingGps = false);
    }
  }

  Future<void> _autoDetectLocationInternational() async {
    setState(() => _isDetectingGps = true);
    try {
      final position = await GpsLocationService().getCurrentPosition();
      if (!mounted) return;
      setState(() {
        _detectedLatitude = position.latitude;
        _detectedLongitude = position.longitude;
      });
      _showToast('Location detected');
    } on LocationException catch (e) {
      if (mounted) _showToast(e.message, isError: true);
    } catch (_) {
      if (mounted) _showToast('GPS unavailable. Please try again.', isError: true);
    } finally {
      if (mounted) setState(() => _isDetectingGps = false);
    }
  }

  // ── Customer register: validate & send OTP ────────────────────────────────

  Future<void> _onSriLankaCustomerCreateAccount(
      Map<String, String> data) async {
    final phone = data['phone'] ?? '';
    final fullName = data['fullName'] ?? '';
    final nic = data['nic'] ?? '';
    final preciseAddress = data['preciseAddress'] ?? '';

    if (fullName.trim().isEmpty) {
      _showError('Please enter your full name.');
      return;
    }
    if (phone.trim().isEmpty) {
      _showError('Please enter your phone number.');
      return;
    }
    if (_selectedProvince == null) {
      _showError('Please select your Province.');
      return;
    }
    if (_selectedDistrict == null) {
      _showError('Please select your District.');
      return;
    }

    final reg = ref.read(customerRegistrationProvider.notifier);
    reg.setMode(isLogin: false);
    reg.updateFullName(fullName.trim());
    reg.updatePhone(phone.trim());
    reg.updateNic(nic.trim());
    reg.updatePreciseAddress(preciseAddress.trim());
    reg.updateDeliveryNote(data['deliveryNote'] ?? '');
    reg.updateEmail(data['email'] ?? '');
    reg.updateProvince(_selectedProvince);
    reg.updateDistrict(_selectedDistrict);

    await reg.sendOtp();

    if (!mounted) return;
    final state = ref.read(customerRegistrationProvider);
    if (state.hasError) {
      _showError(state.error!);
      return;
    }
    _go(_FigmaAuthPage.sriLankaCustomerRegisterOtp);
  }

  Future<void> _onInternationalCustomerCreateAccount(
      Map<String, String> data) async {
    final email = data['email'] ?? '';
    final fullName = data['fullName'] ?? '';

    if (fullName.trim().isEmpty) {
      _showError('Please enter your full name.');
      return;
    }
    if (email.trim().isEmpty || !email.contains('@')) {
      _showError('Please enter a valid email address.');
      return;
    }

    final reg = ref.read(customerRegistrationProvider.notifier);
    reg.setMode(isLogin: false);
    reg.updateFullName(fullName.trim());
    reg.updateEmail(email.trim());
    reg.updatePhone(data['phone'] ?? '');
    reg.updatePreciseAddress(data['preciseAddress'] ?? '');
    reg.updateDeliveryNote(data['deliveryNote'] ?? '');

    await reg.sendOtp();

    if (!mounted) return;
    final state = ref.read(customerRegistrationProvider);
    if (state.hasError) {
      _showError(state.error!);
      return;
    }
    _go(_FigmaAuthPage.internationalCustomerRegisterOtp);
  }

  // ── Customer login: send OTP ──────────────────────────────────────────────

  Future<void> _onSriLankaCustomerSendOtp() async {
    final phone = _loginPhoneCtrl.text.trim();
    if (phone.isEmpty) {
      _showError('Please enter your phone number.');
      return;
    }

    final exists =
        await ref.read(authProvider.notifier).checkCustomerExists(phone);
    if (!mounted) return;
    if (!exists) {
      _showError('No account found for this number. Please register.');
      return;
    }

    final reg = ref.read(customerRegistrationProvider.notifier);
    reg.setMode(isLogin: true);
    reg.updatePhone(phone);
    await reg.sendOtp();

    if (!mounted) return;
    final state = ref.read(customerRegistrationProvider);
    if (state.hasError) {
      _showError(state.error!);
      return;
    }
    _go(_FigmaAuthPage.sriLankaCustomerLoginOtp);
  }

  Future<void> _onInternationalCustomerSendOtp() async {
    final email = _loginEmailCtrl.text.trim();
    if (email.isEmpty || !email.contains('@')) {
      _showError('Please enter a valid email address.');
      return;
    }

    final exists =
        await ref.read(authProvider.notifier).checkCustomerExists(email);
    if (!mounted) return;
    if (!exists) {
      _showError('No account found for this email. Please register.');
      return;
    }

    final reg = ref.read(customerRegistrationProvider.notifier);
    reg.setMode(isLogin: true);
    reg.updateEmail(email);
    await reg.sendOtp();

    if (!mounted) return;
    final state = ref.read(customerRegistrationProvider);
    if (state.hasError) {
      _showError(state.error!);
      return;
    }
    _go(_FigmaAuthPage.internationalCustomerLoginOtp);
  }

  // ── OTP success handlers ──────────────────────────────────────────────────

  Future<void> _onCustomerLoginOtpSuccess(String otp) async {
    // Real OTP verification via provider
    final ok = await ref.read(customerRegistrationProvider.notifier).verifyOtp(otp);
    if (!mounted) return;
    if (!ok) {
      _showError(ref.read(customerRegistrationProvider).error ?? 'Incorrect OTP. Please try again.');
      return;
    }
    final regState = ref.read(customerRegistrationProvider);
    final contact = regState.data.primaryContact;
    try {
      await ref.read(authProvider.notifier).loginCustomerOtp(contact: contact);
      if (!mounted) return;
      context.go(RouteNames.customerHome);
    } catch (e) {
      if (!mounted) return;
      _showError(e.toString().replaceAll('Exception: ', ''));
    }
  }

  Future<void> _onCustomerRegisterOtpSuccess(String otp) async {
    // Real OTP verification via provider
    final ok = await ref.read(customerRegistrationProvider.notifier).verifyOtp(otp);
    if (!mounted) return;
    if (!ok) {
      _showError(ref.read(customerRegistrationProvider).error ?? 'Incorrect OTP. Please try again.');
      return;
    }
    final regState = ref.read(customerRegistrationProvider);
    try {
      await ref.read(authProvider.notifier).register(
            fullName: regState.data.fullName,
            email: regState.data.email,
            phone: regState.data.phone,
            password: '',
            role: UserRole.customer,
            nic: regState.data.nic,
            detectedCountry: regState.data.overrideInfo.detectedCountry,
            selectedCountry: regState.data.overrideInfo.selectedCountry,
            countryOverride: regState.data.overrideInfo.isCountryOverride,
            detectionSource: regState.data.overrideInfo.detectionSource,
            riskFlag: regState.data.overrideInfo.riskFlag,
            verifiedPhone: regState.data.overrideInfo.verifiedPhone || regState.data.isLkUser,
            verifiedEmail: regState.data.overrideInfo.verifiedEmail || !regState.data.isLkUser,
            deliveryCountry: regState.data.country,
            deliveryProvince: _selectedProvince?.name ?? regState.data.province?.name,
            deliveryDistrict: _selectedDistrict?.name ?? regState.data.district?.name,
            deliveryApproxArea: regState.data.approxArea,
            deliveryPreciseAddress: regState.data.preciseAddress,
            deliveryNote: regState.data.deliveryNote,
          );
      if (!mounted) return;
      // Save default delivery address so customer home can use it immediately
      final user = ref.read(currentUserProvider);
      if (user != null) {
        final defaultAddress = CustomerDeliveryAddress.fromUserFields(
          customerId: user.id,
          deliveryProvince: _selectedProvince?.name ?? regState.data.province?.name,
          deliveryDistrict: _selectedDistrict?.name ?? regState.data.district?.name,
          deliveryApproxArea: regState.data.approxArea,
          deliveryPreciseAddress: regState.data.preciseAddress,
          deliveryNote: regState.data.deliveryNote,
        );
        await ref
            .read(customerDeliveryAddressProvider.notifier)
            .saveDefaultAddress(defaultAddress);
      }
      if (!mounted) return;
      context.go(RouteNames.customerHome);
    } catch (e) {
      if (!mounted) return;
      _showError(e.toString().replaceAll('Exception: ', ''));
    }
  }

  // ── OTP resend handlers ─────────────────────────────────────────────────

  Future<void> _onCustomerResendOtp() async {
    await ref.read(customerRegistrationProvider.notifier).sendOtp();
    if (!mounted) return;
    final state = ref.read(customerRegistrationProvider);
    if (state.hasError) _showError(state.error!);
  }

  Future<void> _onSriLankaCustomerResendOtp() async {
    final phone = _loginPhoneCtrl.text.trim();
    if (phone.isEmpty) return;
    final reg = ref.read(customerRegistrationProvider.notifier);
    reg.updatePhone(phone);
    await reg.sendOtp();
    if (!mounted) return;
    final state = ref.read(customerRegistrationProvider);
    if (state.hasError) _showError(state.error!);
  }

  Future<void> _onInternationalCustomerResendOtp() async {
    final email = _loginEmailCtrl.text.trim();
    if (email.isEmpty) return;
    final reg = ref.read(customerRegistrationProvider.notifier);
    reg.updateEmail(email);
    await reg.sendOtp();
    if (!mounted) return;
    final state = ref.read(customerRegistrationProvider);
    if (state.hasError) _showError(state.error!);
  }

  // ── Vendor login ─────────────────────────────────────────────────────────

  Future<void> _onVendorSignIn(bool rememberMe) async {
    final email = _vendorLoginEmailCtrl.text.trim();
    final password = _vendorLoginPasswordCtrl.text;
    if (email.isEmpty) { _showError('Please enter your email.'); return; }
    if (password.isEmpty) { _showError('Please enter your password.'); return; }

    setState(() => _isVendorLoading = true);
    try {
      // Read the previously stored flag BEFORE this login
      final wasRemembered = await StorageService.getVendorRememberMe();

      final verifiedUser = await ref.read(authProvider.notifier).verifyVendorCredentials(
        email: email,
        password: password,
      );
      if (!mounted) return;
      final authState = ref.read(authProvider);
      if (authState.hasError || verifiedUser == null) {
        _showError(authState.error ?? 'Login failed.');
        return;
      }
      // Block SL-registered vendors from logging in via international mode
      final isInternationalPage = _page == _FigmaAuthPage.internationalVendorLogin;
      if (isInternationalPage && verifiedUser.selectedCountry == 'LK') {
        _showError('This account is registered for Sri Lanka. Please use the Sri Lanka login.');
        return;
      }
      // Save the new checkbox state for future logins / logout popup
      await StorageService.saveVendorRememberMe(rememberMe);
      // Skip OTP only if vendor had Remember Me from a PREVIOUS session
      if (rememberMe && wasRemembered) {
        await _onVendorOtpSuccess('');
      } else {
        _vendorLoginOtpEmail = _maskEmail(email);
        final isLk = _page == _FigmaAuthPage.sriLankaVendorLogin;
        _go(isLk
            ? _FigmaAuthPage.sriLankaVendorLoginOtp
            : _FigmaAuthPage.internationalVendorLoginOtp);
      }
    } catch (e) {
      if (mounted) _showError(e.toString().replaceAll('Exception: ', ''));
    } finally {
      if (mounted) setState(() => _isVendorLoading = false);
    }
  }

  String _maskEmail(String email) {
    final at = email.indexOf('@');
    if (at <= 1) return email;
    final local = email.substring(0, at);
    final domain = email.substring(at);
    final visible = local.length > 3 ? local.substring(0, 3) : local[0];
    return '$visible***$domain';
  }

  // ── Vendor register ───────────────────────────────────────────────────────

  Future<void> _onVendorCreateAccount(Map<String, String> data) async {
    final email = data['email'] ?? '';
    final fullName = data['fullName'] ?? '';
    final password = data['password'] ?? '';
    final confirmPassword = data['confirmPassword'] ?? '';
    final shopName = data['shopName'] ?? '';
    final categories = data['categories'] ?? '';

    if (fullName.trim().isEmpty) { _showError('Please enter your full name.'); return; }
    if (email.trim().isEmpty || !email.contains('@')) { _showError('Please enter a valid email.'); return; }
    if (password.length < 8) { _showError('Password must be at least 8 characters.'); return; }
    if (password != confirmPassword) { _showError('Passwords do not match.'); return; }
    if (shopName.trim().isEmpty) { _showError('Please enter your shop name.'); return; }
    if (categories.trim().isEmpty) { _showError('Please select at least one category.'); return; }

    final lat = double.tryParse(data['latitude'] ?? '');
    final lng = double.tryParse(data['longitude'] ?? '');
    if (lat == null || lng == null) { _showError('Please pin your shop location on the map.'); return; }

    setState(() => _isVendorLoading = true);
    try {
      final isSriLanka = data['country'] == 'Sri Lanka';
      await ref.read(authProvider.notifier).register(
        fullName: fullName.trim(),
        email: email.trim(),
        phone: data['phone'] ?? '',
        password: password,
        role: UserRole.vendor,
        businessName: shopName.trim(),
        categories: categories.isNotEmpty ? categories.split(',') : null,
        shopName: shopName.trim(),
        shopAddress: data['shopAddress'] ?? '',
        shopProvince: data['province']?.isNotEmpty == true ? data['province'] : null,
        shopDistrict: data['district']?.isNotEmpty == true ? data['district'] : null,
        shopLatitude: lat,
        shopLongitude: lng,
        shopLocationSource: 'map_pin',
        businessRegistrationNumber: data['businessRegNo']?.isNotEmpty == true ? data['businessRegNo'] : null,
        detectedCountry: isSriLanka ? 'LK' : 'OTHER',
        selectedCountry: isSriLanka ? 'LK' : 'OTHER',
      );
      if (!mounted) return;
      final authState = ref.read(authProvider);
      if (authState.hasError) {
        _showError(authState.error!);
      } else if (authState.isAuthenticated) {
        context.go(RouteNames.vendorHome);
      }
    } catch (e) {
      if (mounted) _showError(e.toString().replaceAll('Exception: ', ''));
    } finally {
      if (mounted) setState(() => _isVendorLoading = false);
    }
  }

  // ── Vendor forgot-password handlers ────────────────────────────────────────────

  Future<void> _onVendorForgotPasswordSendCode(_FigmaAuthPage otpPage) async {
    final email = _forgotPasswordEmailCtrl.text.trim();
    if (email.isEmpty || !email.contains('@')) {
      _showError('Please enter a valid email address.');
      return;
    }
    setState(() => _isVendorLoading = true);
    try {
      final otp = await ref.read(authProvider.notifier).generateResetOtp(email);
      if (!mounted) return;
      _resetOtp = otp;
      _resetEmail = email;
      _previousPassword = await ref.read(authProvider.notifier).getVendorPassword(email);
      _go(otpPage);
    } catch (e) {
      if (mounted) _showError(e.toString().replaceAll('Exception: ', ''));
    } finally {
      if (mounted) setState(() => _isVendorLoading = false);
    }
  }

  void _onVendorForgotPasswordVerifyOtp(
      String enteredOtp, _FigmaAuthPage newPasswordPage) {
    if (_resetOtp == null || enteredOtp != _resetOtp) {
      _showError('Invalid OTP. Please try again.');
      return;
    }
    _go(newPasswordPage);
  }

  Future<void> _onVendorUpdatePassword(
      TextEditingController passwordCtrl,
      TextEditingController confirmCtrl,
      _FigmaAuthPage loginPage) async {
    final password = passwordCtrl.text;
    final confirm = confirmCtrl.text;
    if (password.length < 8) {
      _showError('Password must be at least 8 characters.');
      return;
    }
    if (password != confirm) {
      _showError('Passwords do not match.');
      return;
    }
    if (_resetEmail == null) {
      _showError('Session expired. Please restart the reset process.');
      return;
    }
    setState(() => _isVendorLoading = true);
    try {
      await ref.read(authProvider.notifier).resetPassword(
            email: _resetEmail!,
            newPassword: password,
          );
      if (!mounted) return;
      final authState = ref.read(authProvider);
      if (authState.hasError) {
        _showError(authState.error!);
        return;
      }
      _resetOtp = null;
      _resetEmail = null;
      _previousPassword = null;
      _forgotPasswordEmailCtrl.clear();
      _newPasswordCtrl.clear();
      _confirmNewPasswordCtrl.clear();
      _showToast('Password updated successfully!');
      _go(loginPage);
    } catch (e) {
      if (mounted) _showError(e.toString().replaceAll('Exception: ', ''));
    } finally {
      if (mounted) setState(() => _isVendorLoading = false);
    }
  }

  Future<void> _onVendorOtpSuccess(String otp) async {
    final email = _vendorLoginEmailCtrl.text.trim();
    final password = _vendorLoginPasswordCtrl.text;
    setState(() => _isVendorLoading = true);
    try {
      await ref.read(authProvider.notifier).login(
        email: email,
        password: password,
        role: UserRole.vendor,
      );
      if (!mounted) return;
      final authState = ref.read(authProvider);
      if (authState.hasError) {
        _showError(authState.error!);
        return;
      }
      context.go(RouteNames.vendorHome);
    } catch (e) {
      if (mounted) _showError(e.toString().replaceAll('Exception: ', ''));
    } finally {
      if (mounted) setState(() => _isVendorLoading = false);
    }
  }

  void _showToast(String message, {bool isError = false}) {
    if (!mounted) return;
    final overlay = Overlay.of(context);
    late OverlayEntry entry;
    entry = OverlayEntry(
      builder: (_) => _ToastOverlay(
        message: message,
        isError: isError,
        onClose: () => entry.remove(),
      ),
    );
    overlay.insert(entry);
    Future.delayed(const Duration(seconds: 4), () {
      if (entry.mounted) entry.remove();
    });
  }

  void _showError(String message) => _showToast(message, isError: true);

  // ── Build ─────────────────────────────────────────────────────────────────

  // Pages that contain heavy maps — kept permanently mounted via Offstage
  static const _persistentPages = {
    _FigmaAuthPage.sriLankaVendorRegister,
    _FigmaAuthPage.internationalVendorRegister,
  };

  @override
  Widget build(BuildContext context) {
    if (_detecting) {
      return const Scaffold(
        backgroundColor: Color(0xFF040504),
        body: Center(
          child: CircularProgressIndicator(color: Color(0xFFFF8213)),
        ),
      );
    }

    final slvReg = _buildPageFor(_FigmaAuthPage.sriLankaVendorRegister);
    final intlReg = _buildPageFor(_FigmaAuthPage.internationalVendorRegister);

    return AnimatedBuilder(
      animation: _animCtrl,
      builder: (context, _) {
        final showPrev = _prevPage != null && _animCtrl.value < 1.0;

        Widget buildSlide(_FigmaAuthPage page, bool isInbound) {
          final isPersistent = _persistentPages.contains(page);
          final child = isPersistent
              ? (page == _FigmaAuthPage.sriLankaVendorRegister ? slvReg : intlReg)
              : _buildPageFor(page);
          return SlideTransition(
            position: isInbound ? _inSlide : _outSlide,
            child: RepaintBoundary(child: child),
          );
        }

        return Stack(
          children: [
            // Keep persistent pages alive but hidden when not active/transitioning
            if (_page != _FigmaAuthPage.sriLankaVendorRegister &&
                !(_prevPage == _FigmaAuthPage.sriLankaVendorRegister && showPrev))
              Offstage(child: TickerMode(enabled: false, child: slvReg)),
            if (_page != _FigmaAuthPage.internationalVendorRegister &&
                !(_prevPage == _FigmaAuthPage.internationalVendorRegister && showPrev))
              Offstage(child: TickerMode(enabled: false, child: intlReg)),
            // Outgoing page
            if (showPrev) buildSlide(_prevPage!, false),
            // Incoming / current page
            buildSlide(_page, true),
          ],
        );
      },
    );
  }

  Widget _buildPageFor(_FigmaAuthPage page) {
    switch (page) {
      // ── Customer: Sri Lanka ───────────────────────────────────────────────
      case _FigmaAuthPage.sriLankaCustomerLogin:
        return SrilankacustomerloginWidget(
          phoneController: _loginPhoneCtrl,
          onSendOtp: _onSriLankaCustomerSendOtp,
          onRegister: () => _go(_FigmaAuthPage.sriLankaCustomerRegister),
          onVendorLogin: () => _go(_FigmaAuthPage.sriLankaVendorLogin),
          onCountryTap: () => _onCountrySwitch(_FigmaAuthPage.internationalCustomerLogin),
        );

      case _FigmaAuthPage.sriLankaCustomerLoginOtp:
        return SrilankacustomerloginotpWidget(
          onVerifyOtp: _onCustomerLoginOtpSuccess,
          onBack: () => _go(_FigmaAuthPage.sriLankaCustomerLogin, back: true),
          maskedPhone: ref.read(customerRegistrationProvider).maskedContact ?? '',
          onResend: _onSriLankaCustomerResendOtp,
        );

      case _FigmaAuthPage.sriLankaCustomerRegister:
        return SrilankacustomerregisteraccountWidget(
          onBack: () => _go(_FigmaAuthPage.sriLankaCustomerLogin, back: true),
          onSignIn: () => _go(_FigmaAuthPage.sriLankaCustomerLogin, back: true),
          onCountryTap: () => _onCountrySwitch(_FigmaAuthPage.internationalCustomerRegister),
          onProvinceTap: _showProvincePicker,
          onDistrictTap: _showDistrictPicker,
          onUseCurrentLocation: _isDetectingGps ? null : _autoDetectLocation,
          isDetectingLocation: _isDetectingGps,
          onCreateAccountWithData: _onSriLankaCustomerCreateAccount,
          selectedProvince: _selectedProvince?.name,
          selectedDistrict: _selectedDistrict?.name,
          initialLatitude: _detectedLatitude,
          initialLongitude: _detectedLongitude,
          onLocationPinChanged: (lat, lng) => setState(() {
            _detectedLatitude = lat;
            _detectedLongitude = lng;
          }),
        );

      case _FigmaAuthPage.sriLankaCustomerRegisterOtp:
        return SrilankacustomerregistrationotpWidget(
          onVerifyOtp: _onCustomerRegisterOtpSuccess,
          onBack: () => _go(_FigmaAuthPage.sriLankaCustomerRegister, back: true),
          maskedPhone: ref.read(customerRegistrationProvider).maskedContact ?? '',
          onResend: _onCustomerResendOtp,
        );

      // ── Customer: International ───────────────────────────────────────────
      case _FigmaAuthPage.internationalCustomerLogin:
        return InternationalcustomerloginWidget(
          emailController: _loginEmailCtrl,
          onSendOtp: _onInternationalCustomerSendOtp,
          onRegister: () => _go(_FigmaAuthPage.internationalCustomerRegister),
          onVendorLogin: () => _go(_FigmaAuthPage.internationalVendorLogin),
          onCountryTap: () => _onCountrySwitch(_FigmaAuthPage.sriLankaCustomerLogin),
        );

      case _FigmaAuthPage.internationalCustomerLoginOtp:
        return InternationalcustomerloginotpWidget(
          onVerifyOtp: _onCustomerLoginOtpSuccess,
          onBack: () => _go(_FigmaAuthPage.internationalCustomerLogin, back: true),
          maskedEmail: ref.read(customerRegistrationProvider).maskedContact ?? '',
          onResend: _onInternationalCustomerResendOtp,
        );

      case _FigmaAuthPage.internationalCustomerRegister:
        return InternationalcustomerregisteraccountWidget(
          onBack: () => _go(_FigmaAuthPage.internationalCustomerLogin, back: true),
          onSignIn: () => _go(_FigmaAuthPage.internationalCustomerLogin, back: true),
          onCountryTap: () => _onCountrySwitch(_FigmaAuthPage.sriLankaCustomerRegister),
          onProvinceTap: _showProvincePicker,
          onDistrictTap: _showDistrictPicker,
          onUseCurrentLocation: _isDetectingGps ? null : _autoDetectLocation,
          isDetectingLocation: _isDetectingGps,
          onCreateAccountWithData: _onInternationalCustomerCreateAccount,
          selectedProvince: _selectedProvince?.name,
          selectedDistrict: _selectedDistrict?.name,
          initialLatitude: _detectedLatitude,
          initialLongitude: _detectedLongitude,
          onLocationPinChanged: (lat, lng) => setState(() {
            _detectedLatitude = lat;
            _detectedLongitude = lng;
          }),
        );

      case _FigmaAuthPage.internationalCustomerRegisterOtp:
        return InternationalcustomerregistrationotpWidget(
          onVerifyOtp: _onCustomerRegisterOtpSuccess,
          onBack: () => _go(_FigmaAuthPage.internationalCustomerRegister, back: true),
          maskedEmail: ref.read(customerRegistrationProvider).maskedContact ?? '',
          onResend: _onCustomerResendOtp,
        );

      // ── Vendor: Sri Lanka ─────────────────────────────────────────────────
      case _FigmaAuthPage.sriLankaVendorLogin:
        return SrilankavendorloginWidget(
          emailController: _vendorLoginEmailCtrl,
          passwordController: _vendorLoginPasswordCtrl,
          onSignIn: _isVendorLoading ? null : _onVendorSignIn,
          isLoading: _isVendorLoading,
          onRegister: () => _go(_FigmaAuthPage.sriLankaVendorRegister),
          onCustomerLogin: () => _go(_FigmaAuthPage.sriLankaCustomerLogin),
          onForgotPassword: () =>
              _go(_FigmaAuthPage.sriLankaVendorForgotPassword),
          onCountryTap: () => _onCountrySwitch(_FigmaAuthPage.internationalVendorLogin),
        );

      case _FigmaAuthPage.sriLankaVendorLoginOtp:
        return SrilankavendorloginotpWidget(
          onVerifyOtp: _onVendorOtpSuccess,
          maskedEmail: _vendorLoginOtpEmail ?? '',
          onBack: () => _go(_FigmaAuthPage.sriLankaVendorLogin, back: true),
        );

      case _FigmaAuthPage.sriLankaVendorRegister:
        return SrilankavendorregistrationWidget(
          onBack: () => _go(_FigmaAuthPage.sriLankaVendorLogin, back: true),
          onSignIn: () => _go(_FigmaAuthPage.sriLankaVendorLogin, back: true),
          onCountryTap: () => _onCountrySwitch(_FigmaAuthPage.internationalVendorRegister),
          onCreateAccountWithData: _isVendorLoading ? null : _onVendorCreateAccount,
          onProvinceTap: _showProvincePicker,
          onDistrictTap: _showDistrictPicker,
          onUseCurrentLocation: _isDetectingGps ? null : _autoDetectLocation,
          isDetectingLocation: _isDetectingGps,
          selectedProvince: _selectedProvince?.name,
          selectedDistrict: _selectedDistrict?.name,
          initialLatitude: _detectedLatitude,
          initialLongitude: _detectedLongitude,
          externalPinPoint: _vendorPinPoint,
          isLoading: _isVendorLoading,
          onLocationPinChanged: (lat, lng) => setState(() {
            _detectedLatitude = lat;
            _detectedLongitude = lng;
            _vendorPinPoint = LatLng(lat, lng);
          }),
        );

      case _FigmaAuthPage.sriLankaVendorRegisterOtp:
        return SrilankavendorregistrationotpWidget(
          onVerifyOtp: _onVendorOtpSuccess,
          onBack: () => _go(_FigmaAuthPage.sriLankaVendorRegister, back: true),
        );

      case _FigmaAuthPage.sriLankaVendorForgotPassword:
        return SrilankavendorforgetpasswordWidget(
          emailController: _forgotPasswordEmailCtrl,
          isLoading: _isVendorLoading,
          onBack: () => _go(_FigmaAuthPage.sriLankaVendorLogin, back: true),
          onSignIn: () => _go(_FigmaAuthPage.sriLankaVendorLogin, back: true),
          onSendResetCode: _isVendorLoading
              ? null
              : () => _onVendorForgotPasswordSendCode(
                    _FigmaAuthPage.sriLankaVendorForgotPasswordOtp,
                  ),
        );

      case _FigmaAuthPage.sriLankaVendorForgotPasswordOtp:
        return SrilankavendorforgetpasswordotpWidget(
          onSignIn: () => _go(_FigmaAuthPage.sriLankaVendorLogin, back: true),
          onBack: () => _go(_FigmaAuthPage.sriLankaVendorForgotPassword, back: true),
          onResendCode: () => _onVendorForgotPasswordSendCode(
            _FigmaAuthPage.sriLankaVendorForgotPasswordOtp,
          ),
          onVerifyCode: (otp) => _onVendorForgotPasswordVerifyOtp(
            otp,
            _FigmaAuthPage.sriLankaVendorNewPassword,
          ),
        );

      case _FigmaAuthPage.sriLankaVendorNewPassword:
        return NewpasswordupdatesrilankavendorWidget(
          passwordController: _newPasswordCtrl,
          confirmPasswordController: _confirmNewPasswordCtrl,
          isLoading: _isVendorLoading,
          previousPassword: _previousPassword,
          onBack: () => _go(_FigmaAuthPage.sriLankaVendorForgotPasswordOtp, back: true),
          onUpdatePassword: _isVendorLoading
              ? null
              : () => _onVendorUpdatePassword(
                    _newPasswordCtrl,
                    _confirmNewPasswordCtrl,
                    _FigmaAuthPage.sriLankaVendorLogin,
                  ),
        );

      // ── Vendor: International ─────────────────────────────────────────────
      case _FigmaAuthPage.internationalVendorLogin:
        return InternationalvendorloginWidget(
          emailController: _vendorLoginEmailCtrl,
          passwordController: _vendorLoginPasswordCtrl,
          onSignIn: _isVendorLoading ? null : _onVendorSignIn,
          isLoading: _isVendorLoading,
          onRegister: () => _go(_FigmaAuthPage.internationalVendorRegister),
          onCustomerLogin: () => _go(_FigmaAuthPage.internationalCustomerLogin),
          onForgotPassword: () =>
              _go(_FigmaAuthPage.internationalVendorForgotPassword),
          onCountryTap: () => _onCountrySwitch(_FigmaAuthPage.sriLankaVendorLogin),
        );

      case _FigmaAuthPage.internationalVendorLoginOtp:
        return InternationalvendorloginotpWidget(
          onVerifyOtp: _onVendorOtpSuccess,
          maskedEmail: _vendorLoginOtpEmail ?? '',
          onBack: () => _go(_FigmaAuthPage.internationalVendorLogin, back: true),
        );

      case _FigmaAuthPage.internationalVendorRegister:
        return InternationalvendorregistrationWidget(
          onBack: () => _go(_FigmaAuthPage.internationalVendorLogin, back: true),
          onSignIn: () => _go(_FigmaAuthPage.internationalVendorLogin, back: true),
          onCountryTap: () => _onCountrySwitch(_FigmaAuthPage.sriLankaVendorRegister),
          onCreateAccountWithData: _isVendorLoading ? null : _onVendorCreateAccount,
          onProvinceTap: _showProvincePicker,
          onDistrictTap: _showDistrictPicker,
          onUseCurrentLocation: _isDetectingGps ? null : _autoDetectLocationInternational,
          isDetectingLocation: _isDetectingGps,
          selectedProvince: _selectedProvince?.name,
          selectedDistrict: _selectedDistrict?.name,
          initialLatitude: _detectedLatitude,
          initialLongitude: _detectedLongitude,
          externalPinPoint: _vendorPinPoint,
          isLoading: _isVendorLoading,
          onLocationPinChanged: (lat, lng) => setState(() {
            _detectedLatitude = lat;
            _detectedLongitude = lng;
            _vendorPinPoint = LatLng(lat, lng);
          }),
        );

      case _FigmaAuthPage.internationalVendorRegisterOtp:
        return InternationalvendorregistrationotpWidget(
          onVerifyOtp: _onVendorOtpSuccess,
          onBack: () => _go(_FigmaAuthPage.internationalVendorRegister, back: true),
        );

      case _FigmaAuthPage.internationalVendorForgotPassword:
        return InternationalvendorforgetpasswordWidget(
          emailController: _forgotPasswordEmailCtrl,
          isLoading: _isVendorLoading,
          onBack: () => _go(_FigmaAuthPage.internationalVendorLogin, back: true),
          onSignIn: () => _go(_FigmaAuthPage.internationalVendorLogin, back: true),
          onSendResetCode: _isVendorLoading
              ? null
              : () => _onVendorForgotPasswordSendCode(
                    _FigmaAuthPage.internationalVendorForgotPasswordOtp,
                  ),
        );

      case _FigmaAuthPage.internationalVendorForgotPasswordOtp:
        return InternationalvendorforgetpasswordotpWidget(
          onSignIn: () => _go(_FigmaAuthPage.internationalVendorLogin, back: true),
          onBack: () => _go(_FigmaAuthPage.internationalVendorForgotPassword, back: true),
          onResendCode: () => _onVendorForgotPasswordSendCode(
            _FigmaAuthPage.internationalVendorForgotPasswordOtp,
          ),
          onVerifyCode: (otp) => _onVendorForgotPasswordVerifyOtp(
            otp,
            _FigmaAuthPage.internationalVendorNewPassword,
          ),
        );

      case _FigmaAuthPage.internationalVendorNewPassword:
        return NewpasswordupdateforinternationalvendorWidget(
          passwordController: _newPasswordCtrl,
          confirmPasswordController: _confirmNewPasswordCtrl,
          isLoading: _isVendorLoading,
          previousPassword: _previousPassword,
          onBack: () =>
              _go(_FigmaAuthPage.internationalVendorForgotPasswordOtp, back: true),
          onUpdatePassword: _isVendorLoading
              ? null
              : () => _onVendorUpdatePassword(
                    _newPasswordCtrl,
                    _confirmNewPasswordCtrl,
                    _FigmaAuthPage.internationalVendorLogin,
                  ),
        );
    }
  }
}

class _DirectionalTween extends Animatable<Offset> {
  final ValueNotifier<double> dirNotifier;
  final bool inbound;
  const _DirectionalTween({required this.dirNotifier, required this.inbound});

  @override
  Offset transform(double t) {
    final dir = dirNotifier.value; // +1 forward, -1 back
    if (inbound) {
      // starts off-screen in the direction of travel, slides to zero
      return Offset(dir * (1.0 - t), 0);
    } else {
      // starts at zero, slides off-screen opposite to travel
      return Offset(-dir * t, 0);
    }
  }
}

class _ToastOverlay extends StatelessWidget {
  final String message;
  final bool isError;
  final VoidCallback onClose;

  const _ToastOverlay({
    required this.message,
    required this.isError,
    required this.onClose,
  });

  // build is below

  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: TextDirection.ltr,
      child: SizedBox.expand(
        child: Align(
          alignment: Alignment.topCenter,
          child: Padding(
            padding: const EdgeInsets.fromLTRB(20, 52, 20, 0),
            child: Material(
              color: Colors.transparent,
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
                decoration: BoxDecoration(
                  color: isError ? const Color(0xFFB71C1C) : const Color(0xFF1B5E20),
                  borderRadius: BorderRadius.circular(12),
                  boxShadow: const [
                    BoxShadow(
                      color: Colors.black26,
                      blurRadius: 10,
                      offset: Offset(0, 4),
                    ),
                  ],
                ),
                child: Row(
                  children: [
                    Icon(
                      isError ? Icons.error_outline_rounded : Icons.check_circle_outline_rounded,
                      color: Colors.white,
                      size: 20,
                    ),
                    const SizedBox(width: 10),
                    Expanded(
                      child: Text(
                        message,
                        style: const TextStyle(
                          color: Colors.white,
                          fontFamily: 'Inter',
                          fontSize: 13.5,
                          fontWeight: FontWeight.w600,
                          height: 1.3,
                        ),
                      ),
                    ),
                    const SizedBox(width: 8),
                    GestureDetector(
                      onTap: onClose,
                      child: const Icon(Icons.close_rounded, color: Colors.white70, size: 18),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
