// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcR1YgQK6MOaQx1O09EfK6K6Es1U0YMNo',
    appId: '1:157048167791:web:a9ec546636b1692a161c9a',
    messagingSenderId: '157048167791',
    projectId: 'speedmart-lanka',
    authDomain: 'speedmart-lanka.firebaseapp.com',
    storageBucket: 'speedmart-lanka.firebasestorage.app',
    measurementId: 'G-WSW9QB6PEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO1Dqn68AAqGsPabiGF5Zc-vHwi6hguNA',
    appId: '1:157048167791:android:79bcb4530e85c470161c9a',
    messagingSenderId: '157048167791',
    projectId: 'speedmart-lanka',
    storageBucket: 'speedmart-lanka.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuPO6ROzLJyHovAEGcyjr1F67Go1J9K-0',
    appId: '1:157048167791:ios:6af333663ccf902a161c9a',
    messagingSenderId: '157048167791',
    projectId: 'speedmart-lanka',
    storageBucket: 'speedmart-lanka.firebasestorage.app',
    iosBundleId: 'com.speedmart.lk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuPO6ROzLJyHovAEGcyjr1F67Go1J9K-0',
    appId: '1:157048167791:ios:9eb6a15be4bbdd39161c9a',
    messagingSenderId: '157048167791',
    projectId: 'speedmart-lanka',
    storageBucket: 'speedmart-lanka.firebasestorage.app',
    iosBundleId: 'com.example.speedmartLanka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcR1YgQK6MOaQx1O09EfK6K6Es1U0YMNo',
    appId: '1:157048167791:web:20a7d55d9b567cb1161c9a',
    messagingSenderId: '157048167791',
    projectId: 'speedmart-lanka',
    authDomain: 'speedmart-lanka.firebaseapp.com',
    storageBucket: 'speedmart-lanka.firebasestorage.app',
    measurementId: 'G-3REL5Q8G3L',
  );
}
