import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/theme/app_text_styles.dart';
import '../../../auth/providers/auth_provider.dart';
import '../../../orders/models/order_model.dart';
import '../../../orders/providers/order_provider.dart';
import '../../../proposals/models/proposal.dart';
import '../../../proposals/providers/proposal_provider.dart';
import '../../../requests/models/shopping_request.dart';
import '../../../requests/providers/request_provider.dart';
import 'package:speedmart_lanka/features/location/providers/location_provider.dart';

class PaymentScreen extends ConsumerStatefulWidget {
  const PaymentScreen({
    super.key,
    required this.proposal,
    required this.requestId,
  });

  final Proposal proposal;
  final String requestId;

  @override
  ConsumerState<PaymentScreen> createState() => _PaymentScreenState();
}

class _PaymentScreenState extends ConsumerState<PaymentScreen> {
  final _formKey = GlobalKey<FormState>();
  late final TextEditingController _addressController;
  late final TextEditingController _phoneController;
  
  PaymentMethod _selectedMethod = PaymentMethod.cashOnDelivery;

  // Card controllers
  final _cardNumberController = TextEditingController();
  final _cardExpiryController = TextEditingController();
  final _cardCvvController = TextEditingController();
  final _cardNameController = TextEditingController();

  bool _isProcessing = false;

  @override
  void initState() {
    super.initState();
    final user = ref.read(currentUserProvider);
    
    // Look up the corresponding request to find the delivery address
    final requestsState = ref.read(requestProvider);
    ShoppingRequest? correspondingRequest;
    try {
      correspondingRequest = requestsState.requests.firstWhere(
        (r) => r.id == widget.requestId,
        orElse: () => requestsState.nearbyRequests.firstWhere(
          (r) => r.id == widget.requestId,
        ),
      );
    } catch (_) {}

    // Check if there is an active delivery location in the shared provider first
    final sharedLocation = ref.read(deliveryLocationProvider);

    final initialAddress = sharedLocation?.streetAddress ?? correspondingRequest?.deliveryAddress ?? '';
    final initialPhone = correspondingRequest?.customerPhone ?? user?.phone ?? '';

    _addressController = TextEditingController(text: initialAddress);
    _phoneController = TextEditingController(text: initialPhone);

    _addressController.addListener(() {
      setState(() {});
    });
  }

  @override
  void dispose() {
    _addressController.dispose();
    _phoneController.dispose();
    _cardNumberController.dispose();
    _cardExpiryController.dispose();
    _cardCvvController.dispose();
    _cardNameController.dispose();
    super.dispose();
  }

  Future<void> _handleConfirmPayment() async {
    if (!_formKey.currentState!.validate()) return;

    final customer = ref.read(currentUserProvider);
    if (customer == null) return;

    setState(() {
      _isProcessing = true;
    });

    if (widget.proposal.status != ProposalStatus.accepted) {
      await ref.read(proposalProvider.notifier).acceptProposal(
            widget.proposal.id,
            widget.requestId,
          );
    }

    // Simulate processing
    await Future.delayed(const Duration(seconds: 2));

    final requestsState = ref.read(requestProvider);
    ShoppingRequest? correspondingRequest;
    try {
      correspondingRequest = requestsState.requests.firstWhere(
        (r) => r.id == widget.requestId,
        orElse: () => requestsState.nearbyRequests.firstWhere(
          (r) => r.id == widget.requestId,
        ),
      );
    } catch (_) {}

    final sharedLocation = ref.read(deliveryLocationProvider);
    final double customerLat = sharedLocation?.latitude ?? correspondingRequest?.latitude ?? 0.0;
    final double customerLng = sharedLocation?.longitude ?? correspondingRequest?.longitude ?? 0.0;

    final order = OrderModel(
      id: '', // Generated by repo
      proposalId: widget.proposal.id,
      requestId: widget.requestId,
      customerId: customer.id,
      vendorId: widget.proposal.vendorId,
      vendorBusinessName: widget.proposal.vendorBusinessName,
      vendorPhone: '+94 77 555 4321', // Revealed mock phone number
      customerName: customer.fullName,
      customerPhone: _phoneController.text,
      deliveryAddress: _addressController.text,
      items: widget.proposal.items,
      deliveryCharge: widget.proposal.deliveryCharge,
      totalPrice: widget.proposal.totalPrice + (widget.proposal.totalPrice - widget.proposal.deliveryCharge) * (0.015 + 0.025 + 0.18),
      paymentMethod: _selectedMethod,
      paymentStatus: _selectedMethod == PaymentMethod.cardPayment
          ? PaymentStatus.paid
          : PaymentStatus.pending,
      status: OrderStatus.preparing,
      createdAt: DateTime.now(),
      vendorLatitude: widget.proposal.vendorLatitude,
      vendorLongitude: widget.proposal.vendorLongitude,
      customerLatitude: customerLat,
      customerLongitude: customerLng,
    );

    try {
      final createdOrder = await ref.read(orderProvider.notifier).placeOrder(order);
      
      setState(() {
        _isProcessing = false;
      });

      if (mounted) {
        _showSuccessDialog(createdOrder);
      }
    } catch (e) {
      setState(() {
        _isProcessing = false;
      });
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Payment failed: ${e.toString()}'),
            backgroundColor: Colors.red,
            behavior: SnackBarBehavior.floating,
          ),
        );
      }
    }
  }

  void _showSuccessDialog(OrderModel order) {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (ctx) {
        final isDark = Theme.of(ctx).brightness == Brightness.dark;
        return AlertDialog(
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
          title: const Row(
            children: [
              Icon(Icons.check_circle, color: AppColors.success, size: 28),
              SizedBox(width: 10),
              Text('Order Confirmed!'),
            ],
          ),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('Your order ${order.id} has been successfully placed.', style: AppTextStyles.bodyMedium(isDark ? AppColors.textPrimaryDark : AppColors.textPrimaryLight)),
              const SizedBox(height: 12),
              Text('Merchant and Delivery details are now unlocked and visible on your tracking screen.', style: AppTextStyles.caption(AppColors.success)),
            ],
          ),
          actions: [
            ElevatedButton(
              style: ElevatedButton.styleFrom(
                backgroundColor: AppColors.customerColor,
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
              ),
              onPressed: () {
                Navigator.pop(ctx); // Close dialog
                context.go('/customer'); // Redirect to customer dashboard
              },
              child: const Text('Go to Dashboard', style: TextStyle(color: Colors.white)),
            ),
          ],
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final primaryText = isDark ? AppColors.textPrimaryDark : AppColors.textPrimaryLight;
    final secondaryText = isDark ? AppColors.textSecondaryDark : AppColors.textSecondaryLight;
    final cardColor = isDark ? AppColors.cardDark : AppColors.cardLight;
    final borderColor = isDark ? AppColors.borderDark : AppColors.borderLight;

    return Scaffold(
      backgroundColor: isDark ? AppColors.backgroundDark : AppColors.backgroundLight,
      appBar: AppBar(
        title: const Text('Checkout & Payment'),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new_rounded),
          onPressed: () => context.pop(),
        ),
      ),
      body: _isProcessing
          ? const Center(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  CircularProgressIndicator(color: AppColors.customerColor),
                  SizedBox(height: 16),
                  Text('Processing Payment securely...', style: TextStyle(fontWeight: FontWeight.bold)),
                ],
              ),
            )
          : Form(
              key: _formKey,
              child: SingleChildScrollView(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Delivery Details Section
                    Text('Delivery Details', style: AppTextStyles.h2(primaryText)),
                    const SizedBox(height: 12),
                    Container(
                      padding: const EdgeInsets.all(16),
                      decoration: BoxDecoration(
                        color: cardColor,
                        borderRadius: BorderRadius.circular(16),
                        border: Border.all(color: borderColor),
                      ),
                      child: Column(
                        children: [
                          if (_addressController.text.trim().isEmpty) ...[
                            Container(
                              padding: const EdgeInsets.all(12),
                              margin: const EdgeInsets.only(bottom: 16),
                              decoration: BoxDecoration(
                                color: Colors.red.withOpacity(0.08),
                                borderRadius: BorderRadius.circular(12),
                                border: Border.all(color: Colors.red.withOpacity(0.2)),
                              ),
                              child: const Row(
                                children: [
                                  Icon(Icons.warning_amber_rounded, color: Colors.redAccent, size: 20),
                                  SizedBox(width: 8),
                                  Expanded(
                                    child: Text(
                                      'No delivery location selected. Please add your delivery location.',
                                      style: TextStyle(
                                        color: Colors.redAccent,
                                        fontSize: 13,
                                        fontWeight: FontWeight.bold,
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                          TextFormField(
                            controller: _addressController,
                            decoration: InputDecoration(
                              labelText: 'Full Delivery Address',
                              border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                              prefixIcon: const Icon(Icons.location_on_outlined),
                            ),
                            validator: (val) {
                              if (val == null || val.trim().isEmpty) {
                                return 'Please add your delivery location';
                              }
                              return null;
                            },
                          ),
                          const SizedBox(height: 16),
                          TextFormField(
                            controller: _phoneController,
                            keyboardType: TextInputType.phone,
                            decoration: InputDecoration(
                              labelText: 'Contact Phone Number',
                              border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                              prefixIcon: const Icon(Icons.phone_outlined),
                            ),
                            validator: (val) {
                              if (val == null || val.isEmpty) return 'Enter contact number';
                              return null;
                            },
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 24),

                    // Payment Method Section
                    Text('Choose Payment Method', style: AppTextStyles.h2(primaryText)),
                    const SizedBox(height: 12),
                    Container(
                      padding: const EdgeInsets.all(8),
                      decoration: BoxDecoration(
                        color: cardColor,
                        borderRadius: BorderRadius.circular(16),
                        border: Border.all(color: borderColor),
                      ),
                      child: Column(
                        children: [
                          RadioListTile<PaymentMethod>(
                            title: Row(
                              children: [
                                const Icon(Icons.local_shipping_outlined, color: AppColors.customerColor),
                                const SizedBox(width: 12),
                                Text('Cash on Delivery (COD)', style: AppTextStyles.bodyMedium(primaryText)),
                              ],
                            ),
                            value: PaymentMethod.cashOnDelivery,
                            groupValue: _selectedMethod,
                            activeColor: AppColors.customerColor,
                            onChanged: (val) {
                              setState(() {
                                _selectedMethod = val!;
                              });
                            },
                          ),
                          const Divider(height: 1),
                          RadioListTile<PaymentMethod>(
                            title: Row(
                              children: [
                                const Icon(Icons.credit_card_outlined, color: AppColors.customerColor),
                                const SizedBox(width: 12),
                                Text('Credit / Debit Card', style: AppTextStyles.bodyMedium(primaryText)),
                              ],
                            ),
                            value: PaymentMethod.cardPayment,
                            groupValue: _selectedMethod,
                            activeColor: AppColors.customerColor,
                            onChanged: (val) {
                              setState(() {
                                _selectedMethod = val!;
                              });
                            },
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 24),

                    // Card Fields (Conditional)
                    if (_selectedMethod == PaymentMethod.cardPayment) ...[
                      Text('Card Information', style: AppTextStyles.h2(primaryText)),
                      const SizedBox(height: 12),
                      Container(
                        padding: const EdgeInsets.all(16),
                        decoration: BoxDecoration(
                          color: cardColor,
                          borderRadius: BorderRadius.circular(16),
                          border: Border.all(color: borderColor),
                        ),
                        child: Column(
                          children: [
                            TextFormField(
                              controller: _cardNumberController,
                              keyboardType: TextInputType.number,
                              decoration: InputDecoration(
                                labelText: 'Card Number',
                                hintText: 'xxxx xxxx xxxx xxxx',
                                border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                              ),
                              validator: (val) {
                                if (val == null || val.isEmpty) return 'Enter card number';
                                return null;
                              },
                            ),
                            const SizedBox(height: 16),
                            Row(
                              children: [
                                Expanded(
                                  child: TextFormField(
                                    controller: _cardExpiryController,
                                    decoration: InputDecoration(
                                      labelText: 'Expiry Date',
                                      hintText: 'MM/YY',
                                      border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                                    ),
                                    validator: (val) {
                                      if (val == null || val.isEmpty) return 'Enter expiry';
                                      return null;
                                    },
                                  ),
                                ),
                                const SizedBox(width: 12),
                                Expanded(
                                  child: TextFormField(
                                    controller: _cardCvvController,
                                    keyboardType: TextInputType.number,
                                    obscureText: true,
                                    decoration: InputDecoration(
                                      labelText: 'CVV',
                                      border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                                    ),
                                    validator: (val) {
                                      if (val == null || val.isEmpty) return 'Enter CVV';
                                      return null;
                                    },
                                  ),
                                ),
                              ],
                            ),
                            const SizedBox(height: 16),
                            TextFormField(
                              controller: _cardNameController,
                              decoration: InputDecoration(
                                labelText: 'Cardholder Name',
                                border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                              ),
                              validator: (val) {
                                if (val == null || val.isEmpty) return 'Enter cardholder name';
                                return null;
                              },
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 24),
                    ],

                    // Pricing breakdown card
                    Builder(
                      builder: (context) {
                        final subtotal = widget.proposal.totalPrice - widget.proposal.deliveryCharge;
                        final serviceCharge = subtotal * 0.015;
                        final sscl = subtotal * 0.025;
                        final vat = subtotal * 0.18;
                        final deliveryCharge = widget.proposal.deliveryCharge;
                        final grandTotal = subtotal + serviceCharge + sscl + vat + deliveryCharge;

                        return Container(
                          padding: const EdgeInsets.all(16),
                          decoration: BoxDecoration(
                            color: cardColor,
                            borderRadius: BorderRadius.circular(16),
                            border: Border.all(color: borderColor),
                          ),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text('Sri Lankan Billing Invoice', style: AppTextStyles.subtitle(primaryText).copyWith(fontWeight: FontWeight.bold)),
                              const Divider(height: 20),
                              Row(
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                children: [
                                  Text('Items Subtotal', style: AppTextStyles.bodyMedium(secondaryText)),
                                  Text('Rs. ${subtotal.toStringAsFixed(2)}', style: AppTextStyles.bodyMedium(primaryText)),
                                ],
                              ),
                              const SizedBox(height: 8),
                              Row(
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                children: [
                                  Text('Shop Delivery Charge', style: AppTextStyles.bodyMedium(secondaryText)),
                                  Text('Rs. ${deliveryCharge.toStringAsFixed(2)}', style: AppTextStyles.bodyMedium(primaryText)),
                                ],
                              ),
                              const SizedBox(height: 8),
                              Row(
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                children: [
                                  Text('Platform Service Charge (1.5%)', style: AppTextStyles.bodyMedium(secondaryText)),
                                  Text('Rs. ${serviceCharge.toStringAsFixed(2)}', style: AppTextStyles.bodyMedium(primaryText)),
                                ],
                              ),
                              const SizedBox(height: 8),
                              Row(
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                children: [
                                  Text('SSCL Tax Levy (2.5%)', style: AppTextStyles.bodyMedium(secondaryText)),
                                  Text('Rs. ${sscl.toStringAsFixed(2)}', style: AppTextStyles.bodyMedium(primaryText)),
                                ],
                              ),
                              const SizedBox(height: 8),
                              Row(
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                children: [
                                  Text('VAT Regulatory Tax (18%)', style: AppTextStyles.bodyMedium(secondaryText)),
                                  Text('Rs. ${vat.toStringAsFixed(2)}', style: AppTextStyles.bodyMedium(primaryText)),
                                ],
                              ),
                              const Divider(height: 20),
                              Row(
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                children: [
                                  Text('Grand Total Payable:', style: AppTextStyles.subtitle(primaryText).copyWith(fontWeight: FontWeight.bold)),
                                  Text('Rs. ${grandTotal.toStringAsFixed(2)}', style: AppTextStyles.h2(AppColors.customerColor)),
                                ],
                              ),
                            ],
                          ),
                        );
                      }
                    ),
                    const SizedBox(height: 30),

                    // Action Button
                    SizedBox(
                      width: double.infinity,
                      height: 52,
                      child: ElevatedButton(
                        style: ElevatedButton.styleFrom(
                          backgroundColor: AppColors.customerColor,
                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                          elevation: 0,
                        ),
                        onPressed: _handleConfirmPayment,
                        child: Text(
                          _selectedMethod == PaymentMethod.cardPayment ? 'Confirm & Pay Securely' : 'Confirm Cash on Delivery',
                          style: AppTextStyles.button(Colors.white),
                        ),
                      ),
                    ),
                    const SizedBox(height: 20),
                  ],
                ),
              ),
            ),
    );
  }
}
